docs/providers.rst

Fix typo in docs

---

docs/advanced.rst
docs/configuration.rst

Thank you for writing such a configurable package! I ended up reading the source to figure out how to set up a user with just email and no username, so I thought I'd make it easier for others.

Small clarifications to how to use email rather than username

---

docs/signals.rst

Some signals were missing in the docs. I have added them, improved sectioning and added the provided args as well. Feel free to improve on the descriptions — they're very basic!

Added docs for missing signals

---

requirements.txt

adds mock >= 1.0.1 to requirements.txt

---

allauth/socialaccount/providers/base.py

Helpful for anyone trying to implement a provider.

Provider: added some docstrings on methods for clarity

---

allauth/socialaccount/providers/spotify/models.py
allauth/socialaccount/providers/spotify/provider.py
allauth/socialaccount/providers/spotify/tests.py
allauth/socialaccount/providers/spotify/urls.py
allauth/socialaccount/providers/spotify/views.py

Tested and working well for me

Add Spotify (OAuth 2) provider

---

allauth/account/views.py

Minor cleanup I came across while reading through the source code.

Minor cleanups

---

allauth/account/tests.py
allauth/account/utils.py

Inactive AND unverified user accounts would trigger sending a verification
email upon login, which is utterly confusing for users. In this scenario
they would have the false perception that verifying their emails will
suffice to be able to log in, when the initial (and blocking) fact is an
admin deactivated their accounts.
They should instead be prevented from receiving any verification emails upon login.

Login: prevent inactive accounts from triggering confirmation emails

---

allauth/socialaccount/providers/windowslive/provider.py

A trivial bugfix and some minor cleanups I spotted on the Windows Live provider.

Windows Live provider fixes

---

allauth/account/managers.py
allauth/socialaccount/providers/coinbase/views.py
allauth/socialaccount/providers/google/provider.py
allauth/socialaccount/providers/oauth/views.py
allauth/socialaccount/providers/paypal/views.py
allauth/socialaccount/providers/vk/views.py

Some dead imports as reported by pyflakes.

Cleanup: removed dead imports

---

allauth/account/forms.py

Fixed hardcoded username length for signupform #883

---

allauth/socialaccount/migrations/0001_initial.py

regenerate the extra_data field in initial migration

---

ChangeLog

Minor typo, very likely caused by copying & pasting.

ChangeLog: fixed typo

---

.travis.yml

This enables [Travis' container-based builds](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), which should speed-up tests.

Travis: switched to container-based builds

---

allauth/account/tests.py

Now it also takes into account possible token failures.

Tests: improved password reset flow

---

allauth/locale/es/LC_MESSAGES/django.po
example/README.rst
example/example/settings.py

Hello,
After doing some local testing debugging an issue I had, I noticed there is a wrong translation for the spanish django.po file, and I also added some extra information in the example's README file.

Minor improvements to example's README. Fixed a spanish translation.

---

allauth/app_settings.py

fix for fix https://github.com/pennersr/django-allauth/issues/830

another fix for context processor socialaccount for django >= 1.8

---

allauth/account/utils.py

SortedDict to OrderedDict, No deprecated Warning now.

---

allauth/account/auth_backends.py
allauth/account/forms.py
allauth/account/utils.py

Use fast python code instead of slow SQL joins. This fixes draining of all CPU followed by "too many connections" on MySQL server. Also fixes hardcoded e-mail in auth_backend as it's customisable via USER_MODEL_EMAIL_FIELD.

Fixes issue #922 "avoid SQL joins"

---

.travis.yml
test_settings.py

Was running some tests for allauth and noticed that there were a couple of potential updates, including adding 1.8 to the build matrix :)

Test config & settings updates

---

docs/signals.rst

https://i.imgur.com/5Xi7L8m.png

this is typo

---

allauth/account/urls.py

According to my knowledge, this url will never be called. I propose to delete it to avoid confusion.

Update urls.py - delete url which will never be called

---

allauth/socialaccount/providers/edmodo/models.py
allauth/socialaccount/providers/edmodo/provider.py
allauth/socialaccount/providers/edmodo/tests.py
allauth/socialaccount/providers/edmodo/urls.py
allauth/socialaccount/providers/edmodo/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

OAuth2 support for [Edmodo](https://www.edmodo.com/).

Adds initial Edmodo OAuth2 support

---

allauth/socialaccount/providers/github/views.py

Github do not retrieve private emails through of profile. Then we need get it using: [/user/emails](https://developer.github.com/v3/users/emails/)

Fix issue #369 - Github private emails

---

allauth/account/forms.py

Add missing placeholder

---

allauth/account/adapter.py
allauth/socialaccount/tests.py
allauth/utils.py

Check if value not in blacklist during unique username generation

---

allauth/socialaccount/providers/stripe/models.py
allauth/socialaccount/providers/stripe/provider.py
allauth/socialaccount/providers/stripe/tests.py
allauth/socialaccount/providers/stripe/urls.py
allauth/socialaccount/providers/stripe/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Support Stripe as OAuth2 provider (Feature #1186)

Stripe OAuth2 provider

---

docs/providers.rst

Changes:
* Replace 'atleast' with 'at least'
* Replace 'attemps' with 'attempts'
* Replace 'Sanbox' with 'Sandbox'
* Replace 'explicitely' with 'explicitly'

Fixed typo in providers.rst

---

allauth/socialaccount/providers/angellist/tests.py

This is a fixup for #1214 because I had an unsaved file in my editor.
</sheepish>

Switch angellist tests to OAuth2TestsMixin.

---

allauth/socialaccount/providers/untappd/client.py
allauth/socialaccount/providers/untappd/provider.py
allauth/socialaccount/providers/untappd/tests.py
allauth/socialaccount/providers/untappd/urls.py
allauth/socialaccount/providers/untappd/views.py
docs/providers.rst
test_settings.py

This is the code I'm using for http://mozlando-beers.herokuapp.com/
PR includes docs & tests too.

new oauth2 provider for untappd.com

---

AUTHORS
allauth/socialaccount/providers/pinterest/models.py
allauth/socialaccount/providers/pinterest/provider.py
allauth/socialaccount/providers/pinterest/tests.py
allauth/socialaccount/providers/pinterest/urls.py
allauth/socialaccount/providers/pinterest/views.py
docs/providers.rst
test_settings.py

Support Pinterest as OAuth2 provider

Add a pinterest provider

---

allauth/account/forms.py
allauth/templates/account/email/password_reset_key_message.txt

Rename context variable for consistency in email templates

---

allauth/socialaccount/views.py

This brings it on parity with all other form views in the project.
Fix #1253.

AJAX-enable ConnectionsView.

---

docs/providers.rst

Fix a typo

---

allauth/account/views.py

Fix import in allauth/account/views.py

Add logout_on_password_change import in allauth/account/views.py

---

allauth/socialaccount/providers/shopify/models.py
allauth/socialaccount/providers/shopify/provider.py
allauth/socialaccount/providers/shopify/tests.py
allauth/socialaccount/providers/shopify/urls.py
allauth/socialaccount/providers/shopify/views.py
allauth/templates/shopify/base.html
allauth/templates/shopify/login.html

I've been using this for a while as an app on top of allauth, it would have been great to have it as part of allauth though, maybe someone else will find it useful

Add Shopify as a provider

---

allauth/socialaccount/providers/asana/provider.py
allauth/socialaccount/providers/asana/tests.py
allauth/socialaccount/providers/asana/urls.py
allauth/socialaccount/providers/asana/views.py
test_settings.py

Add Asana socialaccount provider

---

AUTHORS
docs/installation.rst
docs/overview.rst

Adding Asana to docs; Adding myself to AUTHORS

---

allauth/locale/fi/LC_MESSAGES/django.po

This PR updates the existing Finnish translation. Fixes some typos and adds some new translated strings.

Update Finnish translation

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/battlenet/provider.py
allauth/socialaccount/providers/battlenet/tests.py
allauth/socialaccount/providers/battlenet/urls.py
allauth/socialaccount/providers/battlenet/views.py
docs/overview.rst
docs/providers.rst
test_settings.py

Add Battle.net provider

---

allauth/locale/de/LC_MESSAGES/django.po

There should not be any apostrophe were no letter is elided.
Future TODO: Maybe provide two German language files, one for informal and one for formal addressing.

Remove superfluous apostrophes.

---

allauth/account/app_settings.py
allauth/account/forms.py
allauth/account/tests.py
allauth/socialaccount/providers/eveonline/provider.py
docs/configuration.rst

Add signup email verification, moved password verification to mixin to avoid code duplication

---

allauth/account/forms.py

Remove unused confirmation_key field from signup form.

---

allauth/locale/ky/LC_MESSAGES/django.po

Add Kyrgyz translation

---

allauth/socialaccount/providers/battlenet/provider.py

battlenet: Only set the battletag as username if available

---

docs/configuration.rst

Info to docs on what ACCOUNT_UNIQUE_EMAIL does

---

docs/providers.rst

change Twitter examples towards the bottom to match the example at the top

change Twitter examples towards the bottom to match the example at the top

---

docs/providers.rst

Slipped through unnoticed in PR #1463, sorry.

Fix alphabetical order of Dropbox section (docs)

---

docs/providers.rst

This PR updates the documentation with setup URLs for the Windows Live provider.

Update Windows Live provider setup instructions

---

allauth/locale/fr/LC_MESSAGES/django.po

Reviewed the whole .po file.
Fixed consistency issues, typos, grammar errors and fixed commented out strings.
Changed the translator since the original translation quality was mediocre overall.
The .po file compiles fine.

Fixed 100% of fr locale

---

allauth/socialaccount/providers/battlenet/views.py

Refs HearthSim/HSReplay.net#82

battlenet: Use correct Battle.net API url for China

---

AUTHORS
allauth/locale/ko/LC_MESSAGES/django.po
allauth/socialaccount/providers/doximity/models.py
allauth/socialaccount/providers/doximity/provider.py
allauth/socialaccount/providers/doximity/tests.py
allauth/socialaccount/providers/doximity/urls.py
allauth/socialaccount/providers/doximity/views.py
docs/overview.rst
docs/providers.rst
test_settings.py

Doximity is a professional network for Healthcare professionals in the US.  In many ways similar to LinkedIn but with a healthcare focus.

Added Doximity Oauth2 provider.

---

allauth/socialaccount/providers/dropbox/views.py

Correct typo in documentation for DropboxAPI

---

docs/providers.rst

Add a little more detail for setting up Shopify app callback URLs

Add instruction for setting up Shopify app callback URLs

---

docs/decorators.rst

Quick fix for a spelling mistake in the Decorators section

[docs] Quick fix in decorators.rst

---

allauth/socialaccount/providers/draugiem/provider.py

Endpoint used to return string so everything was fine. Their API is not versioned and i can't seem to find any changelog so there is that. Ping me if you want some kind of test for this.

Cast uid to string.

---

allauth/utils.py

Fix serialization with NULL FileField

---

AUTHORS
allauth/socialaccount/providers/discord/models.py
allauth/socialaccount/providers/discord/provider.py
allauth/socialaccount/providers/discord/tests.py
allauth/socialaccount/providers/discord/urls.py
allauth/socialaccount/providers/discord/views.py
docs/installation.rst
docs/providers.rst
test_settings.py

Added a provider for Discord authentication.

Added Discord

---

allauth/locale/zh_CN/LC_MESSAGES/django.po

update some Chinese translation

update some Chinese translation

---

allauth/socialaccount/providers/github/views.py
docs/providers.rst

This will allow for optionally using with GitHub Enterprise.

Adding GitHub Enterprise Support

---

AUTHORS
allauth/socialaccount/providers/line/provider.py
allauth/socialaccount/providers/line/tests.py
allauth/socialaccount/providers/line/urls.py
allauth/socialaccount/providers/line/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Add Line Provider.
line website : https://line.me

Add Line Provider

---

allauth/socialaccount/providers/naver/provider.py
allauth/socialaccount/providers/naver/tests.py
allauth/socialaccount/providers/naver/urls.py
allauth/socialaccount/providers/naver/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Add Naver Provider.
naver website : http://www.naver.com

Add Naver Provider

---

docs/providers.rst

Provider content and titles were inverted.

Moved 500px & 23andMe below proper section titles

---

docs/advanced.rst
docs/providers.rst

- Fix indentation issue with bulleted list in Advanced chapter
- Add note to Bitbucket about Key vs. client_id in Providers chapter
- Use `code-block` directive for Python code samples
- Reformat code samples (PEP8) and 80-character limit
- Fix markup violations in subtitles, use uniform vertical spacing

[Docs] Add note to Bitbucket provider (Key vs. client_id)

---

AUTHORS
allauth/socialaccount/providers/daum/provider.py
allauth/socialaccount/providers/daum/tests.py
allauth/socialaccount/providers/daum/urls.py
allauth/socialaccount/providers/daum/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Daum: http://www.daum.net/
Thank you for accepting my pull request

Added Daum OAuth2

---

docs/providers.rst

- Add provider config docs for DigitalOcean
- Correct section header markup for daum
Fixes #1612

Add provider config docs for DigitalOcean

---

docs/advanced.rst

@bittner does this give you the gist of how to start customizing a provider?

Add advanced doc section on customizing provider behaviour

---

allauth/account/views.py

https://code.djangoproject.com/ticket/19316 is fixed since 1.5.x
the workaround is not required anymore.

Removed unnecessary workarounds

---

docs/templates.rst

I thought it would be useful to include this, for beginners to Django who aren't expecting to have to look in the source code of a package.

Document that the templates are overridable

---

allauth/socialaccount/helpers.py

I need to give users a little more precise feedback on what has happened when they've gone through a social auth flow, not just "The social account has been connected." regardless of the social account type, or whether the account previously existed or not.
There's no easy way to customize messages on social account connection or update at present. I could throw an ImmediateHttpResponse, but throwing exceptions from signal handling code to change the controlling code's behaviour is very undesirable.
The adapter classes have a `message_context` parameter available on their `add_message` method, but this is seldom used.
This PR simply injects the action and social login into the message context such that I can customize the message right where it should be customized; in the template.
Let …

Add sociallogin and action to account connected message context

---

allauth/socialaccount/providers/facebook/urls.py
allauth/socialaccount/providers/oauth2/urls.py
allauth/socialaccount/urls.py
allauth/urls.py
docs/faq.rst

Avoiding regular expression escaping

url(r'...')

---

allauth/account/forms.py

Addressed Issue #1673 in this PR

fixed #1673

---

AUTHORS
allauth/socialaccount/providers/facebook/views.py
allauth/socialaccount/providers/trello/models.py
allauth/socialaccount/providers/trello/provider.py
allauth/socialaccount/providers/trello/tests.py
allauth/socialaccount/providers/trello/urls.py
allauth/socialaccount/providers/trello/views.py
docs/installation.rst
docs/overview.rst
test_settings.py

hi pennersr, here we implemented the integration with trello.
salu

adding the trello integration

---

allauth/locale/ru/LC_MESSAGES/django.po

Hello!
I have updated russian translation with:
- punctuation fixes
- rephrased some sentences to sound correctly
- typo fixes
- grammar fixes
- translated two new messages (previously empty)
It would be great if you could merge it and make (possibly) new release so we can use fixed translation asap. Thanks!

Updated RU translation

---

allauth/locale/tr/LC_MESSAGES/django.po

Added some Turkish translations for messages that are shown to end users.

Add Turkish translations.

---

allauth/socialaccount/providers/kakao/provider.py
allauth/socialaccount/providers/kakao/tests.py

Today, KAKAO API start to provide the user's email information.
So, I added a feature that gets the email from kakao api

Add a feature getting user's email on KAKAO provider

---

allauth/account/tests.py
allauth/socialaccount/tests.py

Fix DeprecationWarning: Please use assertEqual instead

---

allauth/socialaccount/providers/battlenet/tests.py
allauth/socialaccount/providers/battlenet/views.py

Battle.net provider fixes

---

allauth/compat.py
allauth/socialaccount/providers/authentiq/models.py
allauth/socialaccount/providers/authentiq/provider.py
allauth/socialaccount/providers/authentiq/tests.py
allauth/socialaccount/providers/authentiq/urls.py
allauth/socialaccount/providers/authentiq/views.py
docs/installation.rst
docs/providers.rst
test_settings.py

This should add support for passwordless sign-in via Authentiq ID.

Add support for Authentiq

---

AUTHORS
allauth/socialaccount/providers/dataporten/provider.py
allauth/socialaccount/providers/dataporten/tests.py
allauth/socialaccount/providers/dataporten/urls.py
allauth/socialaccount/providers/dataporten/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Hi, there!
[Dataporten](https://www.uninett.no/en/service-platform-dataporten) is an oAuth2 provider for the education sector in Norway, and I have used it as a custom allauth provider for a couple of months now. If you are interested, I would like to add it as a supported provider.
Unfortunately, I have not been able to [pass the test suite](https://travis-ci.org/JakobGM/django-allauth) (EDIT: Not the case any longer). It fails at trying to fetch a user with multiple logins, possibly related to the handling of refresh tokens.
I have been debugging the issue for a while now, but I hope that you might be able to help me understand where the issue lies before I invest a lot more time on fixing this issue. If PRs with failing test suits are undesirable, I will delete this PR and create an …

Add Dataporten provider

---

allauth/socialaccount/providers/dropbox/provider.py
allauth/socialaccount/providers/dropbox/tests.py
allauth/socialaccount/providers/dropbox/urls.py
allauth/socialaccount/providers/dropbox/views.py
allauth/socialaccount/providers/dropbox_oauth2/__init__.py
docs/providers.rst

Updates dropbox provider to OAuth2 with Dropbox v2 API endpoints

---

allauth/locale/no/LC_MESSAGES/django.po

Created Norwegian translation, Bokmål, 'no-nb', which is one of the following ['Bokmål', 'Nynorsk'] written languages in Norway.
First ever GitHub contribution, so correct me if I'm doing something wrong here :)

Make Norwegian local

---

allauth/locale/he/LC_MESSAGES/django.po

Add missing translations, improve accuracy and consistency.

Improve Hebrew locale

---

AUTHORS
allauth/socialaccount/providers/meetup/provider.py
allauth/socialaccount/providers/meetup/tests.py
allauth/socialaccount/providers/meetup/urls.py
allauth/socialaccount/providers/meetup/views.py
docs/installation.rst
docs/overview.rst
test_settings.py

added Provider meetup

---

allauth/account/forms.py
allauth/account/tests.py

Fix for issue - https://github.com/pennersr/django-allauth/issues/1833
Including test case

Fix for issue #1833

---

allauth/locale/es/LC_MESSAGES/django.po

Conflicts were corrected and translations into Spanish were added

fix .po es

---

allauth/socialaccount/providers/eventbrite/provider.py
allauth/socialaccount/providers/eventbrite/tests.py

fixed Mock response to correspond to EventBrite's documentation as well
and fixed the way the email addresses are handled for the provider

fixed issue #1968

---

allauth/account/adapter.py

The login attempts are only used if LOGIN_ATTEMPTS_LIMIT is set.
If we do not write them at all, this removes the dependency on a cache
altogether if LOGIN_ATTEMPTS_LIMIT is not set.

Do not write login attempts to cache if LOGIN_ATTEMPTS_LIMIT is not set

---

docs/forms.rst
docs/index.rst

I ended up having a need to override a bunch of forms save actions to do extra things and couldn't find much in way of documentation about all the Forms available and how/what is overrideable and the information available within.
I've basically broken down each form, where its used, what information is available, how to override with calling parent methods...etc.

Documentation update with informaton about Forms and overriding.

---

AUTHORS
allauth/socialaccount/providers/agave/provider.py
allauth/socialaccount/providers/agave/tests.py
allauth/socialaccount/providers/agave/urls.py
allauth/socialaccount/providers/agave/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Add AgaveAPI Provider

---

docs/overview.rst

Update requirements docs for python 3.6 support

---

example/example/templates/bootstrap/allauth/socialaccount/connections.html

orphaned tags are removed

---

docs/configuration.rst

Just a quick documentation fix.

Link to the stable django docs

---

docs/forms.rst

Updated docs regarding overriding signup form

---

ChangeLog.rst
allauth/socialaccount/providers/globus/provider.py
allauth/socialaccount/providers/globus/tests.py
allauth/socialaccount/providers/globus/urls.py
allauth/socialaccount/providers/globus/views.py
docs/overview.rst
docs/providers.rst
test_settings.py

feat(socialaccount): Add Globus provider

---

allauth/account/views.py

This PR is necessary for single page applications to handle redirects on logout.

refactor: add ajax functionality to logout

---

allauth/locale/zh_Hans/LC_MESSAGES/django.po

There's a bug in translation which is preventing compilemessages from running

Fix a translation error in Chinese translation

---

AUTHORS
allauth/socialaccount/providers/naver/provider.py

Added the processing when email is provided. If it does not, _process_signup() handles it.

feat(naver): Added extract field, email addresses func

---

allauth/templates/base.html

Converted tabs to spaces

---

allauth/socialaccount/providers/linkedin_oauth2/views.py

As mentioned here: https://developer.linkedin.com/blog/posts/2018/redirecting-oauth-uas
and documented here: https://developer.linkedin.com/docs/oauth2

fix(linkedin): Updated OAuth 2.0 UI urls, closes #2086

---

docs/overview.rst

docs: Correct supported Django versions.

---

AUTHORS
allauth/socialaccount/providers/vimeo_oauth2/provider.py
allauth/socialaccount/providers/vimeo_oauth2/test.py
allauth/socialaccount/providers/vimeo_oauth2/urls.py
allauth/socialaccount/providers/vimeo_oauth2/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
example/example/settings.py
test_settings.py

This patch adds support for the Vimeo OAuth2 provider
https://developer.vimeo.com/api/authentication

providers(vimeo): Added Vimeo OAuth2 Provider

---

allauth/locale/pl/LC_MESSAGES/django.po

Update translation of Polish

---

AUTHORS
allauth/socialaccount/providers/kakao/provider.py
allauth/socialaccount/providers/kakao/tests.py
allauth/socialaccount/providers/kakao/urls.py
allauth/socialaccount/providers/kakao/views.py

Kakao API version up

---

docs/configuration.rst

Make it clear that cooldowns are not expected to work when using HMAC

---

docs/forms.rst

Docs: Add missing disconnect key and form

---

allauth/socialaccount/providers/agave/provider.py
allauth/socialaccount/providers/agave/views.py
docs/providers.rst

- [] (n/a) Javascript code should adhere to [StandardJS](https://standardjs.com).
- [] (n/a) If your changes are significant, please update `ChangeLog.rst`.

fix(agave): make base url a configuration option and tolerate missing fields

---

ChangeLog.rst
allauth/socialaccount/providers/jupyterhub/provider.py
allauth/socialaccount/providers/jupyterhub/tests.py
allauth/socialaccount/providers/jupyterhub/urls.py
allauth/socialaccount/providers/jupyterhub/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(socialaccount): Add JupyterHub OAuth2 provider

---

docs/providers.rst

Duplicated Dwolla description

---

AUTHORS
ChangeLog.rst
allauth/locale/pt_PT/LC_MESSAGES/django.po

Refactor of the pt-PT translations to be in conformity with the new spelling agreement.
Added missing translations.
Alphabetical ordering of authors.

refactor(locale): Refactor translations pt-PT

---

docs/providers.rst

docs(providers.rst): added trello (#2178)

---

allauth/socialaccount/providers/trello/views.py

fix(trello): Fixes the urlquote error in #2178

---

pull_request_template.md

- s/yo/you
- Capitalize S in JavaScript
- add period at end of sentence

fix: correct the PR template

---

docs/faq.rst

Added my three-part series on django-allauth set and configuration in detail.

Updated faq.rst with three articles in third party resources.

---

docs/installation.rst

- [eh] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).

Add Patreon to import list

---

allauth/locale/el/LC_MESSAGES/django.po

Just a small edit to the .po file!

Edit a small typo on greek locale

---

allauth/locale/fa/LC_MESSAGES/django.po

There was Some Typo and wrong word usage which really not
advice by institute of persian language and makes word vague
which fixed.

chore(i18n): Fixed typo and grammar bugs in persian translation

---

docs/installation.rst

Added Microsoft Graph API to import list in docs

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/instagram/provider.py

fix(instagram): Extract the user's full name

---

docs/providers.rst

When trying to setup django-allauth, I stumbled uppon some 'unknown' errors with the only hint being "wrong scope" from the return url. Turns out, I registered the app as v2 of Patreons API. Once I used v1 django-allauth could connect without any problems.
https://github.com/pennersr/django-allauth/issues/2282

Improve documentation for Patreon v1 API requirement

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/nextcloud/provider.py
allauth/socialaccount/providers/nextcloud/tests.py
allauth/socialaccount/providers/nextcloud/urls.py
allauth/socialaccount/providers/nextcloud/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(providers): add nextcloud

---

allauth/socialaccount/providers/openid/utils.py

Fixes https://github.com/pennersr/django-allauth/issues/2274.

fix(openid): decode bytes on Python 3 for Django 2.0

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/facebook/provider.py
allauth/socialaccount/providers/facebook/static/facebook/js/fbconnect.js
docs/providers.rst

feat(facebook): Add SDK_URL setting

---

docs/providers.rst

To prevent confusion due to space-delimited QuickBooks Online scope vs. OpenID params

Update Providers docs to explain how to add QuickBooks scope

---

allauth/socialaccount/models.py

fix(socialaccount) SocialLogin is_existing returns boolean

---

docs/configuration.rst

Note about ACCOUNT_EMAIL_VERIFICATION

---

AUTHORS
allauth/socialaccount/providers/strava/provider.py
allauth/socialaccount/providers/strava/tests.py
allauth/socialaccount/providers/strava/urls.py
allauth/socialaccount/providers/strava/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Added Strava as OAuth2 provider.
This PR is a new version of https://github.com/pennersr/django-allauth/pull/2137 that need improvements.
See more here: https://github.com/LittleBigFrog/django-allauth/pull/1

Added Strava as OAuth2 provider

---

AUTHORS
allauth/socialaccount/templatetags/socialaccount.py
allauth/templates/tests/test_403_csrf.html
allauth/tests.py

- [ X ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
- [ X ] All Python code must be 100% pep8 and isort clean.
- [ X ] Feel free to add yourself to `AUTHORS`.

fix: cases where the 'request' context item may not be present

---

AUTHORS
allauth/socialaccount/providers/openstreetmap/provider.py
allauth/socialaccount/providers/openstreetmap/tests.py
allauth/socialaccount/providers/openstreetmap/urls.py
allauth/socialaccount/providers/openstreetmap/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Added OpenStreetMap as OAuth provider

---

tox.ini

Simplifying versions of Django in Tox

---

allauth/socialaccount/providers/oauth/client.py

fix(socialaccount): OAuth1 callback absolute URI construction.

---

allauth/locale/fr/LC_MESSAGES/django.po

update fr translation

---

allauth/locale/de/LC_MESSAGES/django.po

Gender-German is not standard. It makes the text sometimes confusing
and error-prone. Better do not use it.

fix(translation): Replace gender-German

---

allauth/socialaccount/providers/strava/provider.py
allauth/socialaccount/providers/strava/tests.py

Improve Strava provider:
- Add get_avatar_url
- Update get_profile_url

Strava profile

---

allauth/socialaccount/providers/twitch/provider.py

Fixes the scope issue as mentioned in #2244

fix: updating twitch email scope to new API

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/patreon/provider.py
allauth/socialaccount/providers/patreon/views.py
docs/providers.rst

I've added support for Patreon v2.
Default behaviour is to continue support Patreon v1 unless version is set to 'v2' in settings.

Patreon v2

---

AUTHORS
allauth/socialaccount/providers/exist/provider.py
allauth/socialaccount/providers/exist/tests.py
allauth/socialaccount/providers/exist/urls.py
allauth/socialaccount/providers/exist/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(socialaccount): Added Exist as OAuth2 provider

---

allauth/locale/no/LC_MESSAGES/django.po

fix(translation): Improve Norwegian translations

---

AUTHORS
allauth/socialaccount/providers/ynab/provider.py
allauth/socialaccount/providers/ynab/tests.py
allauth/socialaccount/providers/ynab/urls.py
allauth/socialaccount/providers/ynab/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Added YNAB as provider

---

allauth/locale/it/LC_MESSAGES/django.po

Left untouched several words that may be clearer in english
Now registration is correctly translated

Improved italian translation that has some fuzzy words

---

allauth/locale/pt_BR/LC_MESSAGES/django.po

Added two missing translations and fixed one with wrong capitalization.

fix(i18n): update pt_BR translations

---

AUTHORS
allauth/socialaccount/providers/facebook/locale.py

Change appropiate to appropriate.

---

docs/faq.rst

Update faq.rst - Add youtube video tutorial

---

AUTHORS
allauth/socialaccount/providers/amazon_cognito/provider.py
allauth/socialaccount/providers/amazon_cognito/tests.py
allauth/socialaccount/providers/amazon_cognito/urls.py
allauth/socialaccount/providers/amazon_cognito/utils.py
allauth/socialaccount/providers/amazon_cognito/views.py
docs/overview.rst
docs/providers.rst
test_settings.py

feature: Add Amazon Cognito support

---

setup.py

Missed in #5 maybe
- [n/a] Feel free to add yourself to `AUTHORS`.

chore: Add Django 3 PyPI classifier

---

AUTHORS
allauth/utils.py

fix(templates): Fix #2387 Error when 500 template contains a django-allauth template tag

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/yandex/provider.py
allauth/socialaccount/providers/yandex/tests.py
allauth/socialaccount/providers/yandex/urls.py
allauth/socialaccount/providers/yandex/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Added Yandex Provider

---

allauth/socialaccount/providers/edx/provider.py
allauth/socialaccount/providers/edx/tests.py
allauth/socialaccount/providers/edx/urls.py
allauth/socialaccount/providers/edx/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
example/example/settings.py
test_settings.py

openedx provider

---

docs/advanced.rst

docs(advanced): fix typo: add missing arg 'socialaccount'

---

allauth/locale/ar/LC_MESSAGES/django.po

Fix Arabic locale

---

docs/faq.rst

I combined my three articles related to django-allauth into one and updated it recently. I have updated the link.

Updated faq.rst with updated article link.

---

allauth/locale/es/LC_MESSAGES/django.po

Changes in Spanish translation

---

allauth/socialaccount/providers/untappd/client.py
docs/providers.rst

Fixes issue #2481. Updated documentation as well. 

Allow custom user agent for Untappd auth

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/keycloak/provider.py
allauth/socialaccount/providers/keycloak/tests.py
allauth/socialaccount/providers/keycloak/urls.py
allauth/socialaccount/providers/keycloak/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
example/example/settings.py
test_settings.py

Improvements of this PR https://github.com/pennersr/django-allauth/pull/2412

Fix Keycloak adapter

---

allauth/socialaccount/providers/telegram/provider.py

Changes:
- added method to extract first, second name and nick from data (#2431 )
removed part about providers, since I have not added any.

feat: getting common fields from telegram data

---

docs/installation.rst

* Use new URL's path() instead of old url()
* Use 'python manage.py migrate' instead of './manage.py' since most projects don't use an executable manage.py.
- [-] If your changes are significant, please update `ChangeLog.rst`.
- [-] Feel free to add yourself to `AUTHORS`.

docs: Improve installation guide slightly

---

allauth/templates/account/email/email_confirmation_message.txt

hope you don't mind, even though most zill modify this text

fixed the english

---

ChangeLog.rst
allauth/socialaccount/providers/zoom/provider.py
allauth/socialaccount/providers/zoom/tests.py
allauth/socialaccount/providers/zoom/urls.py
allauth/socialaccount/providers/zoom/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Adding Zoom as an available oauth2 provider.

feat(providers) Add Zoom as a provider

---

ChangeLog.rst
allauth/socialaccount/providers/stocktwits/provider.py
allauth/socialaccount/providers/stocktwits/tests.py
allauth/socialaccount/providers/stocktwits/urls.py
allauth/socialaccount/providers/stocktwits/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

Adds Stocktwits as an available oauth2 provider.
Resolves #2645 

feat(providers): Add Stocktwits as a provider

---

docs/advanced.rst

docs(advanced): add section on changing a providers scopes

---

ChangeLog.rst
allauth/socialaccount/providers/zoho/provider.py
allauth/socialaccount/providers/zoho/tests.py
allauth/socialaccount/providers/zoho/urls.py
allauth/socialaccount/providers/zoho/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(provider): Add zoho as a provider

---

allauth/locale/fa/LC_MESSAGES/django.po

re-translate persian language

---

docs/faq.rst

This is an up-to-date tutorial I've had for a while, first on wsvincent.com and now on learndjango.com.

adding up-to-date tutorial

---

README.rst

grammar update

---

docs/forms.rst

Add `request` as an argument to `save()`

Fix social SignUp form documentation

---

allauth/socialaccount/providers/discord/provider.py

Discord Accounts are dependent on the discriminator to be identifiable.

feat(discord): Added Discord discriminator to to_str

---

allauth/locale/pl/LC_MESSAGES/django.po

Provided missing translations,
Neutralize gendered forms,
Some stylistics.

fix(i18n): Improve Polish translation.

---

allauth/locale/pl/LC_MESSAGES/django.po

Zarejestuj -> Zarejestruj
Fixes #2708

chore(i18n/pl): Fix a typo in Polish translation.

---

allauth/locale/ja/LC_MESSAGES/django.po

[2710] fixing a fuzzy translation in Japanese locale

---

allauth/locale/fr/LC_MESSAGES/django.po

French typo fix

---

allauth/socialaccount/app_settings.py

style: Remove meaningless string concatination

---

allauth/socialaccount/providers/microsoft/tests.py
allauth/socialaccount/providers/microsoft/views.py

fix(microsoft): Raise OAuth2Error when user id not found

---

allauth/socialaccount/providers/telegram/provider.py

fix(telegram): Fixed check for absent fields

---

allauth/locale/pl/LC_MESSAGES/django.po

fix (translations): A few minor corrections in the Polish translation

---

allauth/socialaccount/providers/facebook/provider.py

fix(facebook): Reference previously unused NONCE_LENGTH constant in get_nonce

---

allauth/socialaccount/providers/netiq/provider.py
allauth/socialaccount/providers/netiq/tests.py
allauth/socialaccount/providers/netiq/urls.py
allauth/socialaccount/providers/netiq/view.py
docs/overview.rst
docs/providers.rst
test_settings.py

- [Done] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [Done] Add documentation to `docs/providers.rst`.
- [Done] Add an entry to the list of supported providers over at `docs/overview.rst`.

feat(providers) Add NetIQ/Microfocus AccessManager socialprovider

---

allauth/socialaccount/providers/trainingpeaks/provider.py
allauth/socialaccount/providers/trainingpeaks/tests.py
allauth/socialaccount/providers/trainingpeaks/urls.py
allauth/socialaccount/providers/trainingpeaks/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(provider) add provider TrainingPeaks

---

allauth/locale/cs/LC_MESSAGES/django.po

Fixed wrongly translated "created" for the Czech language.

fix: update cs Django.po

---

allauth/socialaccount/providers/keycloak/views.py
docs/providers.rst

feat(keycloak) : setting for alternative URL

---

docs/advanced.rst

Simply adding documentation of the sign up method that was added in this [commit](https://github.com/pennersr/django-allauth/commit/8c8ea6eae56db22662b514b943e5414e19d732eb#)

docs: add signup to adapter methods

---

allauth/socialaccount/providers/microsoft/provider.py
allauth/socialaccount/providers/microsoft/tests.py
allauth/socialaccount/providers/microsoft/views.py

feat (Microsoft): Use mailNickname as username

---

allauth/locale/id/LC_MESSAGES/django.po

feat(i18n): Add Indonesian translations

---

allauth/locale/eu/LC_MESSAGES/django.po

chore(i18n): Update Basque translation

---

allauth/locale/mn/LC_MESSAGES/django.po

chore (i18n): Addedd Mongolian translation

---

allauth/locale/ka/LC_MESSAGES/django.po

Added Georgian language(ka) localization

Added Georgian language(ka) localization

---

allauth/locale/zh_Hant/LC_MESSAGES/django.po

locale: Added missing translation to zh_Hant

locale: Added missing translation to zh_Hant

---

allauth/locale/ja/LC_MESSAGES/django.po

I updated only translation definitions which I could test on my project which uses django-allauth.

chore(i18n): Update Japanese translation

---

setup.py

Update Django trove classifiers

---

allauth/socialaccount/providers/gitea/provider.py
allauth/socialaccount/providers/gitea/tests.py
allauth/socialaccount/providers/gitea/urls.py
allauth/socialaccount/providers/gitea/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(providers): Add gitea as provider

---

allauth/socialaccount/providers/mediawiki/provider.py
allauth/socialaccount/providers/mediawiki/tests.py
allauth/socialaccount/providers/mediawiki/urls.py
allauth/socialaccount/providers/mediawiki/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
example/example/settings.py
test_settings.py

feat(socialaccount): Add MediaWiki as a provider

---

allauth/socialaccount/providers/line/provider.py
allauth/socialaccount/providers/line/views.py
docs/providers.rst

Line has two api to get user infomation, one is [get user profile](https://developers.line.biz/en/reference/line-login/#get-user-profile), the other is[ verify ID token](https://developers.line.biz/en/reference/line-login/#verify-id-token). If you need user's email, you need to call verify ID token api.
There are three changes:
1. If scope contain `email`, switch api endpoint to verify ID token.
2. use email or uid as username to prevent duplicate username. original version use display name as username, which is easy duplicated.
3. add setting example and update Line document url on providers.rst

fix(line): Fixed scope with email bug 

---

allauth/socialaccount/providers/odnoklassniki/views.py

GitHub issue: https://github.com/pennersr/django-allauth/issues/2949

Replaced http with https for odnoklassniki URL

---

AUTHORS
allauth/socialaccount/providers/gumroad/provider.py
allauth/socialaccount/providers/gumroad/tests.py
allauth/socialaccount/providers/gumroad/urls.py
allauth/socialaccount/providers/gumroad/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(providers): Add gumroad as provider

---

allauth/account/forms.py

fix(accounts): Fix attribute error for custom email field when resetting password

---

allauth/socialaccount/providers/facebook/views.py

https://github.com/pennersr/django-allauth/issues/2986
Closes #2986

refactor(facebook): complete login

---

allauth/templates/account/password_reset_done.html
allauth/templates/account/verification_sent.html
allauth/templates/account/verified_email_required.html

Solves https://github.com/pennersr/django-allauth/issues/2926

Make it clearer for users to check their spam folder if they do not receive password reset or verification emails

---

docs/providers.rst

Since March 1, 2020 Microsoft has depreciated the application registration portal listed here in favor of their azure portal. This URL should lead users to the proper page, see their blog at https://developer.microsoft.com/en-us/identity/blogs/deprecation-of-app-registrations-legacy-experience-and-the-application-registration-portal-apps-dev-microsoft-com/

doc: Update Microsoft application registration endpoint

---

allauth/locale/fr/LC_MESSAGES/django.po

Docfix: The current save signal described doesn't work, I think this should fix it. See pennersr#2277

Fixing save signal on CustomResetPassword form

---

ChangeLog.rst
allauth/locale/ca/LC_MESSAGES/django.po

feat(i18n): add Catalan translations

---

setup.py

`setup.py`: Add project URLs for PyPi

---

allauth/socialaccount/providers/microsoft/models.py
allauth/socialaccount/providers/microsoft/provider.py
allauth/socialaccount/providers/microsoft/views.py

Microsoft Graph Provider was a little outdated and inconsistent to other providers. This pull request updates and refactors the code of Microsoft Graph Provider, by keeping it consistent with the latest updated providers, such as Google. It changes nothing on functionality, only code improvement.
---

refactor(microsoft): Update Microsoft Graph Provider

---

allauth/socialaccount/providers/edx/views.py

fix(edx): update complete_login requests

---

allauth/locale/ka/LC_MESSAGES/django.po

feat(i18n) Update Georgian translation

---

allauth/socialaccount/providers/drip/provider.py
allauth/socialaccount/providers/drip/tests.py
allauth/socialaccount/providers/drip/urls.py
allauth/socialaccount/providers/drip/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(providers): add Drip

---

.github/workflows/ci.yml
docs/overview.rst
setup.py
tox.ini

chore: add python 3.10 support

---

AUTHORS
allauth/socialaccount/providers/snapchat/provider.py
allauth/socialaccount/providers/snapchat/tests.py
allauth/socialaccount/providers/snapchat/urls.py
allauth/socialaccount/providers/snapchat/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
example/example/settings.py
test_settings.py

feat(providers): add snapchat

---

allauth/socialaccount/providers/hubspot/provider.py
allauth/socialaccount/providers/hubspot/tests.py
allauth/socialaccount/providers/hubspot/urls.py
allauth/socialaccount/providers/hubspot/views.py
docs/overview.rst
docs/providers.rst
test_settings.py

feat(providers): add Hubspot

---

setup.py

Use the produciton/stable [PyPI classifier](https://pypi.org/classifiers/), so people don't think this package is beta-quality software.

chore: Classify as Stable on PyPI

---

allauth/locale/pt_BR/LC_MESSAGES/django.po

Included missing pt_BR (Brazilian Portuguese) translations and made a few adjustments to some of the existing pt_BR translations.

fix(locale): update pt_BR translations

---

.github/workflows/ci.yml

* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-node/releases
* https://github.com/actions/setup-python/releases

fix(ci): Upgrade GitHub Actions

---

allauth/locale/ja/LC_MESSAGES/django.po

fix translation in japanese locale

---

allauth/locale/ja/LC_MESSAGES/django.po

Improved Japanese translation

---

ChangeLog.rst
allauth/account/adapter.py
allauth/account/tests.py
allauth/socialaccount/providers/amazon/provider.py
allauth/socialaccount/providers/dwolla/views.py
allauth/socialaccount/providers/eventbrite/provider.py
allauth/socialaccount/providers/facebook/locale.py
allauth/socialaccount/providers/flickr/provider.py
allauth/socialaccount/providers/netiq/views.py
allauth/socialaccount/providers/twitch/tests.py
allauth/socialaccount/providers/windowslive/views.py
allauth/utils.py
docs/configuration.rst
docs/providers.rst
example/example/templates/base.html

[`codespell --ignore-words-list=espace,nam --skip="./.*,*.po"`](https://pypi.org/project/codespell)
CAUTION: There are two changes to `dict.get()` values that require careful review.
* allauth/socialaccount/providers/dwolla/views.py
* allauth/socialaccount/providers/eventbrite/provider.py

fix: Fix typos

---

allauth/socialaccount/providers/netiq/views.py

This reverts an overstep in #3211

fix: Use nam, not name in providers/netiq/views.py

---

allauth/locale/sl/LC_MESSAGES/django.po

I improved Slovenian translations and removed fuzzy

Improve Slovenian translations

---

allauth/socialaccount/providers/wahoo/provider.py
allauth/socialaccount/providers/wahoo/tests.py
allauth/socialaccount/providers/wahoo/urls.py
allauth/socialaccount/providers/wahoo/views.py
docs/installation.rst
docs/overview.rst
docs/providers.rst
test_settings.py

feat(socialaccount): add Wahoo as a social provider

---

allauth/socialaccount/providers/pinterest/provider.py
allauth/socialaccount/providers/pinterest/tests.py
allauth/socialaccount/providers/pinterest/views.py
example/example/settings.py

Hi, I found the `Pinterest` now upgrade the api version to `v5`.  So I add this support.
But this version has some breaking changes. 
1. Authorize url has changed, And `scopes` has changed
2. Not return `uid`, And use the `username` to replace `uid`
3. Profile response structure has changed.
Maybe need drop the `v1` api, What do you think of it? @pennersr 
For now I just make the `v5` works well.
And the migrate docs for `Pinterest` at [Migration](https://developers.pinterest.com/docs/getting-started/migration/)

Feat pinterest

---

allauth/socialaccount/providers/coinbase/provider.py
allauth/socialaccount/providers/coinbase/tests.py
allauth/socialaccount/providers/coinbase/views.py

fix(coinbase): Fixed coinbase v2 API

---

docs/providers.rst

Update Keycloak documentation URL

docs: Update Keycloak documentation URL

---

docs/providers.rst

fix(gitea): typo in provider docs

---

allauth/locale/de/LC_MESSAGES/django.po

chore(i18n): Update German translation

---

allauth/socialaccount/providers/weixin/views.py

fix(weixin): Fixed invalid extra_data

---

allauth/templates/account/base.html

Make string translatable in base.html

---

.github/workflows/ci.yml
setup.py
tox.ini

... and some incidental CI fixes.

Drop support for EOL Python versions (3.5, 3.6), test on Python 3.11

---

allauth/socialaccount/providers/discord/provider.py

Can be done if someone puts data in that field manually

fix(discord): Exit early if extra_data is not a dictionary

---

allauth/locale/el/LC_MESSAGES/django.po

Contribute to the Greek translation

---

docs/advanced.rst

just a simple fix for grammatical error.

fix grammar

---

.github/workflows/ci.yml
AUTHORS
ChangeLog.rst
setup.py
tox.ini

feat: Support Django 4.2

---

docs/faq.rst

Removes a dead link from the FAQ of the documentation.

docs: remove dead link from FAQ

---

allauth/socialaccount/providers/discord/provider.py
allauth/socialaccount/providers/discord/tests.py

Regarding https://github.com/pennersr/django-allauth/issues/3312, added support for new usernames. Also added new tests.

Update Discord Provider for Changes to Username system

---

allauth/locale/pt_PT/LC_MESSAGES/django.po

fix(locale): Fixed signup closed translation

---

docs/advanced.rst

Fixes https://github.com/pennersr/django-allauth/issues/1789.
Ref: https://stackoverflow.com/a/45328687/15690

docs: use staff_member_required to protect admin

---

docs/forms.rst

docs(forms): add request as arguments in save() in MyCustomAddEmailForm Class

---

allauth/locale/sk/LC_MESSAGES/django.po

This patch contains missing slovak translations and fixes few wrong translations.

Add missing slovak translations

---

allauth/locale/es/LC_MESSAGES/django.po

Fixed some errors and added a few missing translations.

fix(locale): fix spanish translations

---

ChangeLog.rst
allauth/socialaccount/providers/questrade/provider.py
allauth/socialaccount/providers/questrade/tests.py
allauth/socialaccount/providers/questrade/urls.py
allauth/socialaccount/providers/questrade/views.py
docs/installation.rst
docs/providers/index.rst
docs/providers/questrade.rst
test_settings.py

feat(providers): add Questrade

---

.github/pull_request_template.md

Update the github pr template file with the new docs/providers/*.rst layout.

chore(github): update pr template new doc providers separated files.

---

.github/workflows/ci.yml
ChangeLog.rst
README.rst
allauth/conftest.py
allauth/socialaccount/providers/base/provider.py
allauth/socialaccount/providers/saml/conftest.py
allauth/socialaccount/providers/saml/provider.py
allauth/socialaccount/providers/saml/tests.py
allauth/socialaccount/providers/saml/urls.py
allauth/socialaccount/providers/saml/utils.py
allauth/socialaccount/providers/saml/views.py
docs/overview.rst
docs/providers/index.rst
docs/providers/saml.rst
example/example/settings.py
setup.cfg
test_settings.py
tox.ini

Add support for SAML 2.0 

---

allauth/account/views.py

Add never_cache decorator to prevent csrf_token caching

---

allauth/locale/ar/LC_MESSAGES/django.po

This adds missing translations for Arabic and fix some typos.

fix(i18n/ar): Update Arabic translation

---

.github/workflows/ci.yml

https://github.com/actions/checkout/releases

fix(ci): Upgrade GitHub Actions checkout@v4

---

docs/socialaccount/providers/openid.rst

per conversation in #3165 switch from `dict()` to `{}` for structures

docs(openid): refactor structures

---

allauth/account/tests/test_signup.py
allauth/account/views.py

This pr adds email prefilling suport in signup form, closes #2861

feat(accounts): Added prefilling of forms with GET query strings

---

docs/socialaccount/configuration.rst

docs: update dead link in Social Accounts / Configuration

---

allauth/locale/uk/LC_MESSAGES/django.po

Closes #3469
- [] All Python code must formatted using Black, and clean from pep8 and isort issues.

fix(i18n): Fix i18n for Ukrainian language

---

allauth/locale/pl/LC_MESSAGES/django.po

Language updates only. This PR encompasses all phrases translated into Polish.

Update Polish translation

---

allauth/locale/pt_PT/LC_MESSAGES/django.po

The original Portuguese from Portugal translation was very outdated (11 years old).

Update Portuguese from Portugal translation

---

allauth/locale/pt_PT/LC_MESSAGES/django.po

Fixed all the fuzzy translations in the PT-pt translation file.
Tweaked a few terms.
Filled in most missing translations.

fix(translations): Fixed fuzzies in PT-pt

---

allauth/locale/tr/LC_MESSAGES/django.po

added few new turkish translation and fixed fuzzies

fixed fuzzies in tr

---

allauth/account/middleware.py

fix(account/middleware): AccountMiddleware async capable

---

docs/common/templates.rst

docs(templates): fixed a typo

---

AUTHORS
allauth/locale/ru/LC_MESSAGES/django.po

This pull request includes fixes in django.po file for 'ru' locale. #, fuzzy issues have been addressed, and empty msgstr have been populated. Please review.

fix(i18n): Updates to django.po for ru locale

---

allauth/account/adapter.py

fix(account/adapter): fix a typo in clean_password

---

docs/account/configuration.rst

Fix broken link in account settings

---

.github/dependabot.yml

Automates changes to `.github/workflows/ci.yml`
```diff
steps:
- uses: actions/checkout@v4
-   - uses: actions/setup-node@v3
+   - uses: actions/setup-node@v4
if: ${{ matrix.extra-env == 'standardjs' }}
with:
node-version: '8'
- name: Set up Python 3.11
-     uses: actions/setup-python@v4
+     uses: actions/setup-python@v5
```
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

fix (ci): Keep GitHub Actions up to date with GitHub's Dependabot

---

allauth/account/middleware.py

fix(account): Async session access

---

allauth/locale/ja/LC_MESSAGES/django.po

I fetched the main branch from pennersr/django-allauth and replaced the Japanese language file in it.
And then executed command `python manage.py compilemessages` and it worked fine.
So please check it out again.
Sorry for the inconvenience caused.

ja lang file.

---

examples/regular-django/README.rst

Update instructions after:
https://github.com/pennersr/django-allauth/commit/9db04472b82d1cc0174c4ae02006785fd0a995eb
- [ x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).

docs(example): Update regular-django example README

---

allauth/locale/ja/LC_MESSAGES/django.po

Udpated lang file only.
Confirmed that `python manage.py compilemessages -l ja` worked properly.

ja po file updated

---

allauth/account/utils.py

Don't check Redirect Url if there's no Redirect

---

allauth/locale/fr/LC_MESSAGES/django.po

Updated as per latest changes, to have 100% translated in next release.
Cheers for your work

Update french translation

---

allauth/socialaccount/helpers.py
allauth/socialaccount/models.py

Postpones auto connect during email authentication until after `pre_social_login()`.

refactor(socialaccount): auto connect after pre_social_login

---

allauth/mfa/internal/flows/recovery_codes.py
allauth/mfa/internal/flows/totp.py

Adds request to MFA flows
- Updated based on changes from extraction of MFA flows (prior PR #3677)
- Makes consistent with existing comments in allauth.mfa.signals
```
authenticator_added = Signal()
authenticator_removed = Signal()
authenticator_reset = Signal()
```

fix(mfa): Add request to MFA signals

---

allauth/socialaccount/views.py

refactor(social) Move login_required for ConnectionsView

---

AUTHORS
ChangeLog.rst
allauth/socialaccount/providers/atlassian/provider.py
allauth/socialaccount/providers/atlassian/tests.py
allauth/socialaccount/providers/atlassian/urls.py
allauth/socialaccount/providers/atlassian/views.py
docs/installation/quickstart.rst
docs/socialaccount/providers/atlassian.rst
docs/socialaccount/providers/index.rst
test_settings.py

- **feat(atlassian): add atlassian oauth2 provider**
- **chore(atlassian): add atlassian provider documentation**

feat(atlassian): add atlassian oauth2 provider

---

docs/socialaccount/providers/authelia.rst
docs/socialaccount/providers/index.rst

docs(socialaccount): add config example for Authelia

---

allauth/templates/allauth/elements/field.html

A typo fix in templates/elements/field.html
**First-contribute-ever**

fix(templates): Quotation typo fix

---

ChangeLog.rst

This was added in 8172ea9 but removed in 80088ce, but is still necessary.
All N/A

docs: Add 0.62.0 Backwards Incompatibility Message

---

allauth/locale/zh_Hans/LC_MESSAGES/django.po

Updated zh_Hans i18n.

---

allauth/account/stages.py
allauth/socialaccount/providers/base/provider.py
allauth/socialaccount/providers/base/views.py
allauth/socialaccount/providers/facebook/provider.py
allauth/socialaccount/providers/oauth2/provider.py
allauth/socialaccount/providers/oauth2/views.py
allauth/socialaccount/providers/openid/forms.py
allauth/utils.py

* Adding some types/annotations makes IDEs complain a little less.
* Mypy was also complaining when a superclass implies a field is `None` but it gets assigned to something else in a subclass.
* On that note, Mypy was also complaining about imports done via implicit re-exports, so those get fixed too.

fix: add types for fields overridden in subclasses & correct some imports

---

allauth/headless/account/tests/test_session.py
allauth/headless/internal/sessionkit.py

fix(headless): Do not create an empty session on logout

---

docs/account/configuration.rst

docs: Typo niave > naive

---

ChangeLog.rst
allauth/account/decorators.py
allauth/account/tests/test_decorators.py
allauth/socialaccount/tests/test_connect.py
docs/common/admin.rst
examples/regular-django/example/urls.py
tests/regular/urls.py

Add secure_admin_login() decorator

---

allauth/templates/account/email.html

add form tags for email

---

allauth/socialaccount/providers/atlassian/provider.py

feat(atlassian): add user's name as account string representation

---

docs/socialaccount/signals.rst

This should prevent further misconceptions as in #3834

docs: Add note when social_account_added is called

---

allauth/socialaccount/providers/kakao/provider.py
allauth/socialaccount/providers/kakao/tests.py

fix(kakao): Change deprecated properties to profile information

---

docs/common/admin.rst

It was unclear to me and would have made the instructions easier to follow.

Update admin.rst 

---

docs/account/rate_limits.rst

Add a tip about unit tests and possible problems because of the rate limits (see https://github.com/pennersr/django-allauth/issues/3893)

docs: add a tip about unit tests and rate limits

---

allauth/socialaccount/tests/__init__.py

tests(socialaccount): Extract get_access|refresh_token

---

allauth/mfa/views.py

style(mfa): fix spelling error

---

examples/regular-django/example/templates/allauth/layouts/manage.html

The socialaccount app is optional, so links to it should be conditionally rendered.

chore(templates): Make the example menu handle optional apps

---

allauth/account/middleware.py

fix(account): middleware vs SynchronousOnlyOperation

---

allauth/locale/uk/LC_MESSAGES/django.po

---
Hi, after talking on reddit I decided to use django-allauth again.
Updated the localisation file for my native language. Translated 100%, the original essence is preserved. I use it for several of my sites. Does this change make sense?

refactor: update ukrainian localisation

---

allauth/socialaccount/providers/saml/provider.py
docs/socialaccount/providers/saml.rst

Update provider to allow forcing the email to be pulled from the nameID

---

allauth/locale/fa/LC_MESSAGES/django.po

better translate with native language person.

Update django.po better translate with native language person from Perian(Farsi)

---

docs/socialaccount/providers/saml.rst

Follows: https://github.com/pennersr/django-allauth/pull/4014
I hope these tips and notes help someone in the future. SAML is very particular and secure (which is good!), but these tips for a new project would have helped me immensely. Thanks for your efforts!

docs: add tips and notes for SAML configuration and troubleshooting.

---

allauth/locale/ko/LC_MESSAGES/django.po

This PR is related to ko locale translation.

fix(locale): fix korean translations

---

allauth/templates/account/reauthenticate.html

Same as `mfa/reauthenticate.html`

chore(mfa): add tags to submit button

---

docs/socialaccount/providers/google.rst

fix(google): Fixed example HTML in google.rst

fix(google): Fixed example HTML in google.rst

---

allauth/locale/ko/LC_MESSAGES/django.po

소셜 is better than 서드파티 for korean.
General korean don't know what third-pary is.
So I changed it to 소셜.

fix(locale): fix typo and translation clearer
