AUTHORS, allauth/account/forms.py, allauth/socialaccount/providers/__init__.py, allauth/socialaccount/providers/google/tests.py, allauth/urls.py, allauth/utils.py
This addresses a DeprecationWarning in Django 1.8. It falls back to the
importlib provided in django.utils, as there are still versions of
Django that support Python <= 2.6.
=> Prefer stdlib importlib

allauth/account/adapter.py, allauth/account/utils.py, allauth/socialaccount/adapter.py, allauth/socialaccount/helpers.py, allauth/tests.py
Current default parameter values are evaluated at function definition
time, thus enabling shared mutable state. This is very dangerous as the
code is unpredictable and can end up in unexpected behavior. Using
immutable objects as default parameters avoids nasty surprises.
Refs. http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html#default-parameter-values
=> Bugfix: avoid using mutable objects as default parameter values

allauth/socialaccount/providers/douban/models.py, allauth/socialaccount/providers/douban/provider.py, allauth/socialaccount/providers/douban/tests.py, allauth/socialaccount/providers/douban/urls.py, allauth/socialaccount/providers/douban/views.py
I'm a django web developer from China. After trying a lot of auth apps for django, I find django-allauth is the best one of them which saves me a lot of time for the signup and accounts stuff.  
I tried to fork django-allauth to support douban on one of my site: http://feedfree.me/  , and it works well for me. I hope douban support can be merged to the official repo, so a lot of Chinese sites can use it later.
PS: sorry, last time, I didn't notice the tests.py and forgot to change it. Now, it should pass the test.
=> add douban provider, which is a very popular social site in China

allauth/socialaccount/providers/oauth2/client.py
I'm working on an update to the Dropbox provider, so that it'll work with OAuth2, and noticed that Dropbox doesn't work with the `scope` attribute.
I'm hoping this fix will be able to easily take care of that issue and at the same time not affect other providers.
My thinking is that if the key is empty the remote side ought to accept the value even when missing, having some kind of default.
=> Strip away empty params in OAuth2 client on login

allauth/account/utils.py, allauth/account/views.py, allauth/socialaccount/models.py, allauth/socialaccount/providers/oauth/client.py, allauth/socialaccount/providers/oauth2/views.py, allauth/socialaccount/providers/openid/views.py, allauth/socialaccount/templatetags/socialaccount.py, allauth/utils.py
This removes references to request.REQUEST. It should be be completely backwards compatible (it prefers values in request.POST, etc).
Tests pass locally, and I've done _some_ manual testing, but it does impact some code that is not currently covered by the test suite (specifically in the OAuth providers), so please review with care.
=> Remove references to (now deprecated) request.REQUEST

allauth/socialaccount/south_migrations/0012_auto__chg_field_socialtoken_token_secret.py
Running ./manage.py migrate with django 1.4.19, south 1.0.2, django-allauth 0.19.1 and python 2.7.3 returns :
```
Running migrations for socialaccount:
- Migrating forwards to 0012_auto__chg_field_socialtoken_token_secret.
> socialaccount:0012_auto__chg_field_socialtoken_token_secret
Traceback (most recent call last):
File "./manage.py", line 14, in <module>
execute_manager(settings)
File "/home/www/pikacode.com/shared/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
utility.execute()
File "/home/www/pikacode.com/shared/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/www/pikacode.com/shared/env/local/lib/python2.7/site-pa …
```
=> Fix migration error

allauth/templates/account/email/email_confirmation_message.txt, allauth/templates/account/email/email_confirmation_subject.txt, allauth/templates/account/email/password_reset_key_message.txt
Fixes #822: Confirm email lands in SPAM
=> Change wording in e-mail templates to avoid being classified as SPAM

allauth/socialaccount/models.py
When I was in the admin of my site, I saw the field label for token is "Social account", which doesn't make sense. I think it should be just "token", right? It's just copied from some where else.
=> fix verbose_name of field token in SocialToken

allauth/socialaccount/providers/base.py
Rationale: it's unused and undocumented, and only adds confusion.
=> Cleanup: removed dead code

allauth/account/tests.py
This verifies the login behavior when trying to sign in with an inactive account and `EmailVerificationMethod` is set to `MANDATORY`.
Fixes #841.
=> Added test for unverified ajax login

allauth/socialaccount/providers/base.py
As per the `sociallogin_from_response()` method, it's required to implement the `extract_uid()` method, but besides the call there's no reference to it in the base class. This commit enforces `extract_uid()` to be implemented by providers.
=> Provider: added base `extract_uid()` method

.gitignore, allauth/account/adapter.py, allauth/utils.py, docs/advanced.rst
* Sometime users want to change the validation rules for the username. This lets the user configure `allauth` to use a custom regex for generating a unique username.
=> Added support for custom username regexes

allauth/account/tests.py
Actually this wasn't testing against an unverified account, but against an
inactive account — allauth makes the distinction.
Follow-up of #859.
=> Tests: fixed ajax unverified test

docs/configuration.rst
Easy to miss out that this setting only works after sign up.
=> Docs: added extra details for `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION`

allauth/account/tests.py
Tests that user will be able to either
* log in and therefore be redirected to `settings.LOGIN_REDIRECT_URL` (optional verification), or
* reach the email verification view (mandatory verification)
Also removed the empty `test_login_view()` test.
=> Added tests for verified and unverified login attempts

allauth/socialaccount/migrations/0001_initial.py
This commit edits the first migration to use `registry.as_choices()` for the `choices` argument. `makemigrations` will no longer create migrations files when a provider is removed or added.
=> Stop creation of extraneous migration files

allauth/account/forms.py
I've only noticed this when email is optional, and also using
django-bootstrap3.
The bootstrap3 default render checks the widget's `is_required` status,
which is only initialised in the django field constructor.  So, setting
field.required to False after initialisation still leaves
`widget.is_required` in the default state of True, which then causes the
bootstrap renderer to mistakenly add a required=required attribute.
=> Unset email widget's is_required status too

allauth/account/tests.py
I've previously used ordinary `assert` calls (sorry I'm used to py.test mostly), which don't contain extra information when tests fail. This commit switches them for their `self.assert*()` counterparts.
=> Cleanup: use `self.assert*()` functions

allauth/account/forms.py, allauth/account/tests.py, allauth/account/views.py
This allows to reuse the handlers for XHR responses, and therefore return an error message with a 400 status code when the token is invalid.
Note that this implements the alternative approach as suggested in #894.
Fixes #890.
=> Password reset: perform token validation via form

allauth/account/tests.py
Spotted that I was using `assertEqual()` instead of `assertTrue()` only after my last PR was merged. Also, some tests don't require overriding settings that are already set at the class level.
=> Minor test cleanups

allauth/account/views.py
This relates to #799.
If a user's already authenticated when an AJAX request is made to either ``LoginView`` or ``SignupView`` an ``HttpResponseRedirect`` is returned. This is due to the fact that ``RedirectAuthenticatedUserMixin`` does not process the request to check if it's AJAX.
=> RedirectAuthenticatedUserMixin does not handle AJAX request correctly when user is already authenticated

docs/providers.rst
Also make the link unversioned, which FB will redirect to latest.
=> Repair link to use reStructuredText markup.

allauth/socialaccount/providers/facebook/provider.py, allauth/socialaccount/providers/facebook/static/facebook/js/fbconnect.js, allauth/socialaccount/providers/facebook/templates/facebook/channel.html, allauth/socialaccount/providers/facebook/tests.py, allauth/socialaccount/providers/facebook/urls.py, allauth/socialaccount/providers/facebook/views.py
Minor changes related to the "new" Facebook JS SDK
+ Use "new" Facebook JS SDK 
See Upgrading Web Apps (JavaScript) https://developers.facebook.com/docs/apps/upgrading/
+ Remove unused FB.init params
https://developers.facebook.com/docs/javascript/reference/FB.init/
+ Removing Facebook channelUrl, since it is not supported since long.
https://developers.facebook.com/blog/post/2013/11/21/platform-updates--new-design-for-follow-button-and-like-box--ios-sdk-improvements-and-more/
=> Upgrade to latest Facebook JS SDK

allauth/account/adapter.py, allauth/account/forms.py, allauth/account/tests.py, allauth/account/views.py, allauth/socialaccount/models.py, allauth/socialaccount/tests.py, allauth/socialaccount/views.py, allauth/utils.py, example/example/demo/models.py
Django 1.8 will break if using sites framework
- https://docs.djangoproject.com/en/1.8/ref/contrib/sites/#get-current-site-shortcut
- https://github.com/django/django/blob/1.8/django/contrib/sites/models.py#L50
When using django 1.8 on settings without a ``SITE_ID``, an exception will be raised.
Tthis is permitted in 1.8, since django introduces [get_current_site](https://docs.djangoproject.com/en/1.8/ref/contrib/sites/#get-current-site-shortcut) support in ``get_current`` method in the Manager through the newly-added ``request`` kwarg.
> Changed in Django 1.8:
> This function will now lookup the current site based on request.get_host() if the SITE_ID setting is not defined.
Backward compatible with < 1.8.
=> Fix django 1.8 RequestSite error on LoginView

allauth/app_settings.py
As per #952, here is a proposed change so the context processor check works with an un-migrated django 1.8 settings file.
While I was at it, I also cleaned up the error message.
=> Context processor check fix ups.

docs/installation.rst
Docs changed to accommodate that accordingly for those running 1.8+
Changes committed in:
modified:   docs/installation.rst
=> Approach to adding Context Processors changed in Django 1.8+

allauth/socialaccount/providers/google/tests.py, allauth/socialaccount/providers/google/views.py
- if google responds to you with  a 401 where your token is no good,
raise an `HTTPError` (resp.raise_for_status) so that you can handle
the exception corretly.  Otherwise you just get a 500 stauts because
of a `KeyError`.
=> Respect Google Provider's HTTP reponse

allauth/account/views.py, allauth/templates/account/email.html
Fixes a 500 error when submitting the email_list form without an address selected.
Pre-selects the user's only email address when they have no primary address set.
=> Minor changes to account email view

AUTHORS, allauth/account/app_settings.py, allauth/account/views.py, docs/configuration.rst
Since Django 1.7, if the SessionAuthenticationMiddleware is enabled, the session is invalidated when the user changes the account's password.
Starting Django 2.0, session verification will become mandatory whether or not the SessionAuthenticationMiddleware is enabled.
I figured this may be a good time to add this setting.
[Source: Session invalidation on password change](https://docs.djangoproject.com/en/1.8/topics/auth/default/#session-invalidation-on-password-change)
=> Add ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE setting

.travis.yml, allauth/socialaccount/providers/baidu/models.py, allauth/socialaccount/providers/baidu/provider.py, allauth/socialaccount/providers/baidu/tests.py, allauth/socialaccount/providers/baidu/urls.py, allauth/socialaccount/providers/baidu/views.py, test_settings.py
The Baidu OAuth2 authentication document is here:
1. http://developer.baidu.com/wiki/index.php?title=docs/oauth/refresh
2. http://developer.baidu.com/wiki/index.php?title=docs/oauth/rest/file_data_apis_lista
Baidu developer platform provides several set of useful APIs, for example
the PCS API could be used to operate user's Cloud Storage.
=> Add support for Baidu provider

README.rst
The badge hosting at 'pypip.in' has been broken for a while now
=> Replace pypip badges with shield.io ( badges/pypipins#37 )

allauth/socialaccount/providers/orcid/views.py, docs/providers.rst
Currently there is no documentation for the ORCID provider. It seems
that some things have changed since the ORCID provider was written and
these are some notes to make integrating it easier.
=> Documentation for ORCID integration

allauth/socialaccount/providers/flickr/provider.py, allauth/socialaccount/providers/oauth/client.py, allauth/socialaccount/providers/oauth/provider.py, allauth/socialaccount/providers/oauth/views.py, docs/providers.rst
Flickr apparently requires an app to pass a 'perms' parameter when authenticating, even though the API documentation states that it is optional. Users can now configure this for flickr (and any other OAuth provider) with the AUTH_PARAMS setting. This works the same way as the existing functionality for OAuth2 providers.
=> Allow user to specify extra auth parameters for Flickr (and generic OAuth) providers

docs/showcase.rst
A few of the examples no longer resolve, and those are deleted.  All others still resolve.
=> DNS resolution fails (nxdomain) for the deleted lines.

allauth/socialaccount/providers/orcid/provider.py
extract_from_dict fails when one of the intermediate values is None, raising a TypeError that was not caught properly. This happens when the some of the information is not present in the profile (e.g. the email address that can be hidden).
=> ORCID provider: fix extract_from_dict

allauth/account/models.py
Make sure we use the proper decorator for an atomic transaction across all Django versions.
=> Maintain atomic transactions across django 1.4 to 1.8

docs/installation.rst
I missed it when I just went "for the goods" and didnt realize it was a requirement until my models failed validation.
=> Need more clarity for requirement of sites.

test_settings.py
`django.core.context_processors.request` is deprecated since Django 1.8. 
It's suggested to remove it in django version >= 1.8 case to avoid confusion.
=> Remove deprecated django.core.context_processors.request

allauth/socialaccount/providers/facebook/views.py, docs/providers.rst
The JS SDK returns a short-lived (hours) token. This is fine for
client-side use, but not as suitable for storing in the database.
Add the EXCHANGE_TOKEN setting (False by default for now) to immediately
upgrade to a long-lived token before storing in the SocialToken record.
=> Enable exchanging short-lived FB token for long-lived.

allauth/account/context_processors.py, allauth/app_settings.py, allauth/socialaccount/context_processors.py, allauth/socialaccount/templatetags/socialaccount.py, allauth/templates/account/login.html, allauth/templates/socialaccount/snippets/provider_list.html, docs/changelog.rst, docs/installation.rst, docs/templates.rst, example/example/settings.py, test_settings.py
This basically removes the need to use a ctx processor even if sites don't need it.
It also removes the empty ctx processor from `allauth.account`.
Fixes #949.
=> Replace social account ctx processor with template tag

.travis.yml
Perhaps this is a bit premature, but if you feel like dropping test coverage for deprecated Django versions, here's the merge button...
=> Don't test deprecated Django/Python versions

example/example/templates/bootstrap/allauth/account/login.html, example/example/templates/uniform/allauth/account/login.html
Removed reliance on context_processors from Bootstrap and Uniform examples; fixes #949.
=> Removed remaining reliance on context_processors

allauth/account/tests.py, allauth/account/utils.py
Fix for #994 
Basically add some tests for the uuid field serialization in the urls, and force casting to string on the user_pk_to_url_str method
=> Add UUID support for password reset

allauth/account/app_settings.py, allauth/account/views.py, docs/configuration.rst
As discussed in #735, this PR adds the option to automatically sign users in after they have reset their password successfully.
Based on the opinions on the issue, the default for `LOGIN_ON_EMAIL_CONFIRMATION` has also been adjusted to `False`.
=> Added option to automatically sign in after password reset

allauth/socialaccount/providers/twitch/provider.py
To generate a Django user (username, first name, last name etc.) from a first-time login with a social account, user data extracted from the Twitch API is used. The extra common fields 'username' and 'name' are mapped as following to the Django user:
* username = Django user's unique username
* name = split(' ') up in parts, name[0] is first name etc.
That seems fine.
Currently Twitch API's JSON data contains a field 'name' and a field 'display_name'.
'name' is fixed and also represents the channel's name/channel URL.
'display_name' can be changed by users as often as they want. (They are only able to change capitalization - however there are Twitch staff members which have a 'display_name' being totally different from their 'name'.)
*Sources:*
* …
=> Correct data extraction for Twitch username fields

allauth/account/tests.py, allauth/account/views.py
Fixes a typo that results in an error when enabling ACCOUNT_LOGIN_ON_PASSWORD_RESET
=> Fix LOGIN_ON_PASSWORD_RESET

allauth/account/utils.py
Return the user.pk as str which contains 36chars UUID. This fixes attribute not found error on user.pk.hex when using UUIDField (Django 1.8).
=> Check if user.pk is already a string

allauth/socialaccount/providers/twitch/views.py
I think this is the fix which needs to be applied as discussed in https://github.com/pennersr/django-allauth/issues/1052.
=> Send client_id with Twitch requests (closes #1052)

allauth/account/urls.py, allauth/socialaccount/providers/facebook/urls.py, allauth/socialaccount/providers/openid/urls.py, allauth/socialaccount/providers/persona/urls.py, allauth/socialaccount/urls.py, allauth/urls.py, docs/installation.rst, example/example/urls.py
Addresses various warnings running against Django 1.8.4:
> `RemovedInDjango110Warning`: `django.conf.urls.patterns()` is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of `django.conf.urls.url()` instances instead.
* `allauth/socialaccount/providers/oauth2/urls.py`
* `allauth/socialaccount/providers/oauth/urls.py`
The `default_urlpatterns` are using `patterns` and the string prefix argument and the string view argument to `url`, which is also deprecated, requiring the callable to be passed instead. As such, I wanted to ask how you wanted that handled before progressing?
=> Remove deprecated `patterns` calls from URL confs

.travis.yml, allauth/socialaccount/providers/oauth/urls.py, allauth/socialaccount/providers/oauth2/urls.py
Follows up from #1116. Clears up remaining `patterns` calls.
=> Clear up remaining `patterns` calls

.gitignore, tox.ini
This allows running the same test matrix that Travis does, but locally.
Rather than upload a report to coveralls this generates an html report
in `./htmlcov`.
Python versions can be installed on Ubuntu using
https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
=> Add Tox support, reflecting Travis tests

allauth/socialaccount/helpers.py, allauth/socialaccount/providers/openid/views.py
render also wraps the context in a RequestContext, but works with the Jinja2 template backend in Django 1.8. Fixes #1133.
See [source of shortcuts.py](https://github.com/django/django/blob/master/django/shortcuts.py), and [deprecation note for context-instance](https://docs.djangoproject.com/en/1.8/releases/1.8/#dictionary-and-context-instance-arguments-of-rendering-functions).
=> Use render instead of render_to_response

allauth/__init__.py, allauth/account/templatetags/account_tags.py, allauth/account/tests.py, allauth/socialaccount/providers/google/tests.py, allauth/socialaccount/templatetags/socialaccount_tags.py
This is minimum changes to make it work under Python 3:
* Importing mock library for different Python versions
* Explicit relative imports.
However, I still could not make it work with Django 1.9. It raises a `KeyError` exception:
=> Fix Python3 related issues

allauth/socialaccount/fields.py
Fixes #1117
* Removes deprecated metaclass. 
* Adds `from_db_value` (which just calls `to_python` — _plus ca change_...)
Test suite passed locally but I wasn't sure of the coverage here — will the JSON storage be exercised? If not I can add a test case for the field itself. 
I could move the duplicated code into a mixin but [very shortly](https://www.djangoproject.com/download/#supported-versions) everything in the <1.8 branch can just be deleted. Happy to follow your guidance.
=> Adjust JSONField for Django >=1.8

allauth/socialaccount/providers/facebook/provider.py, allauth/socialaccount/providers/facebook/tests.py
Sometimes the Facebook profile data looks simply like this:
{"id": "123456", "name": "Harvey McGillicuddy"}
In that case, the User object gets created without any name data, and the
resulting username looks something like "user17". Extracting the name
field in `FacebookProvider.extract_common_fields()` allows
`DefaultSocialAccountAdapter.populate_user()` to insert reasonable
first_name, last_name and username fields.
=> Extract 'name' from Facebook data

allauth/account/utils.py
The test if the PK is str-like by using .to_python fails on OneOnOneFields/ForeignKeys, because they don't override .to_python, and just return the value without validating. Since a concrete subclass of Django's user model is a pretty common custom user model, this can happen fairly often.
The code in UserTokenForm._get_user() obfuscates this issue, because it encounters a ValueError on the call to User.objects.get(pk=pk), while actually expecting the url_str_to_user_pk call (and the .to_python call within) to be the one throwing a ValueError. Thus any tokens generated by users with a PK larger than 9 will be rejected as invalid/expired tokens, and such users are not able to reset their passwords.
The fix below uses the .to_python of the field pointed to by the PK for validation.
=> Custom user models whose primary key was also a foreign key unable to reset their password.

allauth/account/adapter.py, allauth/account/utils.py, allauth/account/views.py, allauth/socialaccount/helpers.py
I am hitting issues using allauth in a pure API capacity. I do not support sessions/session auth on the API, only token-based auth. The problem is that allauth assumes the availability of `request.session` in several places.
In most instances I've been able to customize my adapters to avoid this dependency on sessions without loss of functionality. The rest are interactions with sessions in utility functions, which I cannot easily override.
This change is just shifting a little logic around to allow me to avoid hitting sessions in those remaining cases.
=> Moving account user stashing and logout logic to the DefaultAccountAdapter

allauth/account/views.py
In Django 1.9, form is no longer passed explicitly to FormView's
get_context_data. Instead, we need to call super(...).get_context_data
for it to be populated.
I understand that allauth does not yet support Django 1.9 (the test
suite has numerous failures), but this at least gets us a small step
closer and to is -- to the best of my knowledge -- backwards compatible.
Fixes #1142.
=> Call super().get_context_data early to access form

.travis.yml
For the time being, let them fail without causing the test suite in its
entirety to fail. This lets us track our progress towards Django 1.9
compatibility.
=> Run tests against Django 1.9b1

allauth/account/app_settings.py, allauth/account/tests.py, allauth/account/views.py, docs/configuration.rst
Allows choosing if you want logged in users to be redirected in login/signup pages.
=> Added ACCOUNT_FORCE_REDIRECT_IF_LOGGED_IN option

allauth/socialaccount/providers/oauth2/client.py
OAuth2Client sends `scope` as part of the request for an access token. However, this appears to be against [RFC 6749](https://tools.ietf.org/html/rfc6749.html#section-4.1.3) when `grant_type` is "`authorization_code`".
I'm trying to integrate with the Firefox Accounts service, these Access Token requests are rejected with an error. This patch seems to fix the problem. [The service docs for FxA](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token) appear to agree with [RFC 6749](https://tools.ietf.org/html/rfc6749.html#section-4.1.3) on this.
But, I'm only working with one particular OAuth2 service for my application (i.e. FxA). So, I'm unsure if there are services that expect `scope` to be included
=> OAuth2Client: Do not include `scope` in request for access_token

.travis.yml, tox.ini
* Removed Django 1.6 from testing. It is unsupported. See (https://www.djangoproject.com/download/)
* Added Python 3.5 to the list of Python versions to test against. It is supported since Django 1.8.6 (https://docs.djangoproject.com/en/1.8/releases/1.8.6/)
* Removed `--use-mirrors` from pip install command in the Travis config since it is deprecated. (https://github.com/pypa/pip/pull/1098) 
Current Python 3.5 build fails (https://travis-ci.org/Ecno92/django-allauth/jobs/89953488). It seems that one of the providers (openid) is not Python 3.5 compatible. Since this package has a dependency on it I would suggest to keep it failing until `python-openid` resolves the issue. 
Please let me know if it is necessary to open up a issue at the `python-openid` project. I didn't investigate this …
=> Cleanup and update Travis and Tox file

docs/advanced.rst
Replace 'adddress' with 'address'
=> Fixed typo in advanced.rst

.travis.yml, allauth/socialaccount/tests.py, tox.ini
This failed in Travis on another PR, see
https://github.com/pennersr/django-allauth/pull/1214 and
https://travis-ci.org/pennersr/django-allauth/jobs/94960086
It has nothing to do with that PR but here's the fix, so that one won't appear
to be failing.
Note I thought that Django upstream had decided on 2.0 after 1.9, but then found this which says the next version will be 1.10 https://www.djangoproject.com/weblog/2015/jun/25/roadmap/
=> Repair tests on python-3.4 with django-1.9.

allauth/socialaccount/providers/instagram/views.py, docs/providers.rst
According to the [API documentation](https://www.instagram.com/developer/authentication/), the URLs for oauth should be https://api.instagram.com
Also, added a touch of documentation for the provider.
=> Fix for Instagram provider

allauth/socialaccount/providers/github/provider.py, allauth/socialaccount/providers/github/tests.py
The GitHub provider will currently return `None` if coerced to a string, because
`to_str` returns `name` from the response data. GitHub may return `null` in this
field though, which ultimately results in exceptions coercing to Unicode.
=> Fix GitHub provider to_str on null field responses

AUTHORS, allauth/socialaccount/providers/gitlab/models.py, allauth/socialaccount/providers/gitlab/provider.py, allauth/socialaccount/providers/gitlab/tests.py, allauth/socialaccount/providers/gitlab/urls.py, allauth/socialaccount/providers/gitlab/views.py, docs/providers.rst, test_settings.py
This GitLab provider enables OAuth2 authentication against GitLab. Use following settings in your `DJANGO_SETTINGS_MODULE ` to use your private GitLab server as an OAuth2 provider. 
GITLAB_USER_AUTHORIZATION_URL = 'https://your.gitlab.server.tld/oauth/authorize'
GITLAB_ACCESS_TOKEN_URL = 'https://your.gitlab.server.tld/oauth/token'
GITLAB_USER_INFO_URL = 'https://your.gitlab.server.tld/api/v3/user'
=> Gitlab provider

allauth/account/utils.py, allauth/account/views.py, docs/changelog.rst, docs/configuration.rst
This makes "setting the password" and "changing the password" behave
identically with regards to settings.ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE.
Fix #1262.
=> Don't log user out when setting the password.

MANIFEST.in
I'd like to provide an official django-allauth package in the Debian archive.
Having the tests and documentation sources in the tarball would allow me to
utilize both during package build, running the tests and building the
documentation from source.
=> Include test settings and documentation in source tarball.

allauth/account/adapter.py
The email subject formatting tries to get current site if EMAIL_SUBJECT_PREFIX is not configured. And it use get_current_site() without passing request as parameter which brings "ImproperlyConfigured at ... You're using the Django "sites framework" without having set the SITE_ID setting." error in case SITE_ID is not set (which is okay in case we have sites configured in DB and use request to obtain the current site). But we already have current_site in context so I suggest to use this to fix the problem.
=> Fixed formatting email subject in multisite environment.

allauth/socialaccount/providers/google/provider.py
This pull request provides new magical incantation to 1) force consent screen prompt and 2) request refresh token.
The current `approval_prompt=force` argument will prompt for consent screen/reauthentication. However, this was previously (through 2015?) also the recommended way to request refresh token. Google apparently no longer provides refresh token unless you also explicitly pass `access_type=offline`.
* Refresh token doc: https://developers.google.com/identity/protocols/OpenIDConnect#refresh-tokens
* Consent screen prompt doc: https://developers.google.com/identity/protocols/OpenIDConnect#re-consent
I believe most people will still find old issues suggesting to pass `action=reauthenticate` when they want refresh token -- which will not work but for this new pull request / updated …
=> Adds prompt=consent for Google provider per (newer) docs for refresh token

allauth/account/views.py
The default for `get` is `None`, making this explicit param unnecessary.
=> Remove superfluous 'None' default param to 'get'.

docs/overview.rst
Travis currently tests 2.7, 3.2, 3.3, 3.4, 3.5; the documentation should reflect this.
=> Update Python requirements to reflect Travis testing

allauth/socialaccount/migrations/0003_extra_data_default_dict.py, allauth/socialaccount/models.py
This adds a Django migration but not a South migration, since the former
recognizes the change to the model but the latter doesn't.
=> Change extra_data default from '{}' to dict. Fixes #1272

allauth/socialaccount/south_migrations/0013_auto__chg_field_socialaccount_uid__chg_field_socialapp_secret__chg_fie.py
This supports projects running django 1.6, until allauth stops supporting that
version.
=> Add south migration for UID length changes.

AUTHORS, allauth/socialaccount/providers/fxa/provider.py, allauth/socialaccount/providers/fxa/views.py, docs/providers.rst
Add ``SOCIALACCOUNT_PROVIDERS`` configuration items so that [non-production Firefox Accounts deployments](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction#Firefox_Accounts_deployments) can easily be used. This formalizes the extended ``fxa`` provider used on the Mozilla projects [browsercompat](https://github.com/mdn/browsercompat/tree/master/bcauth/socialaccount/providers/fxa) and [push-dev-dashboard](https://github.com/mozilla-services/push-dev-dashboard/tree/master/dashboard/socialaccount/providers/fxa).
=> Expand Firefox Accounts provider configuration

allauth/account/app_settings.py, allauth/account/tests.py, allauth/account/views.py, allauth/socialaccount/tests.py, allauth/socialaccount/views.py, docs/configuration.rst
I've recently begun using the Jade template language with my Django projects using pyjade. I also use django-allauth in all my projects. The problem I was facing was that the allauth account views use the `.html` extension, but I need to use the `.jade` extension. My first workaround was to import the allauth views, set the `template_name` attribute to my desired template, then call the as_view() method and add my views to my urls.py. However, this solution is proving unwieldy when moving it across many different projects.
I have since edited the views.py of django-allauth to include a `DynamicTemplateExtensionMixin` class and an `ACCOUNT_TEMPLATE_EXTENSION` configuration setting. This way I can easily override the allauth account templates as I did to prior to using Jade and merely have …
=> Add ACCOUNT_TEMPLATE_EXTENSION option and view mixin for allowing other template engine extensions

allauth/compat.py, allauth/socialaccount/providers/facebook/provider.py, allauth/socialaccount/providers/persona/provider.py
These two modules were using a version of `render_to_string` that is
deprecated since Django 1.8.
=> Support overriding two templates with non-Django templates.

allauth/account/adapter.py
To keep consistent with django's regex rule. See  [#1321](https://github.com/pennersr/django-allauth/issues/1321)
=> Remove re.UNICODE

allauth/account/adapter.py, allauth/account/utils.py
I'm using allauth to power a traditional webui as well as an API. I've had to subclass the hell out of the adapters to get the exact behaviour I want, but this is what they're intended to allow. Allauth has been a fantastic help. Particularly on the API front however, I have consistently run into inflexibility in allauth due to the utils.py and helpers.py style of logic containment.
This PR is patching yet another single instance of this inflexibility, but I'd also like to underscore how problematic logic not being in the adapters has been for me when trying to subclass and sensibly customize allauth for usage in an API. That's all :)
=> Keep inactive user response logic in adapter

allauth/socialaccount/providers/orcid/views.py, docs/providers.rst
This closes #1083 by introducing two parameters in the settings. This also fixes the bug mentioned in the documentation. The documentation has been updated to reflect this.
The default behavior of the provider is kept the same.
=> ORCID: endpoint can be changed from the settings

docs/views.rst
When I started with django-allauth I miss documentation of prepared views. So I write it down.
=> Document existing views

allauth/socialaccount/helpers.py
Signup closed and authentication error helpers weren't using the new ACCOUNT_TEMPLATE_EXTENSION feature correctly. This commit makes sure that also those templates can be configured to use custom template extension.
=> Add two missing ACCOUNT_TEMPLATE_EXTENSION suffix

allauth/socialaccount/providers/orcid/views.py
API v1.1 is deprecated on sandbox.orcid.org, v1.2 has been released more than a year ago, and the changes between the two do not affect the behavior of the provider, so we definitely want to switch.
For the record, the changelog is here: https://members.orcid.org/api/news/xsd-12-update
=> Use ORCID API v1.2 instead of v1.1

AUTHORS, allauth/socialaccount/providers/eveonline/models.py, allauth/socialaccount/providers/eveonline/provider.py, allauth/socialaccount/providers/eveonline/tests.py, allauth/socialaccount/providers/eveonline/urls.py, allauth/socialaccount/providers/eveonline/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
Not even sure if this is the sort of provider you'd want included, but I added an [Eve Online](http://www.eveonline.com) provider using their [SSO API](https://eveonline-third-party-documentation.readthedocs.org/en/latest/sso/index.html). This API is a little different from most of the other providers in that a single person can authenticate with multiple identities (any of their characters in-game)[0]. The biggest difference that most users of django-allauth might encounter is that there is not a way to get an email address for a user.
The biggest area I'm looking for review is how I'm mapping a character's information to a user in `providers.py`. Is there other information I should be extracting? The only information I can easily get is a character's name, an ID number for that …
=> Add Eve Online provider

allauth/account/forms.py, allauth/account/tests.py
Set the maxlength attribute of the username field's widget in the init method, since we have to delay field initialization until all the apps are loaded. Fixes issue #1395.
=> Set maxlength attribute of username signup input

AUTHORS, allauth/socialaccount/providers/slack/provider.py, allauth/socialaccount/providers/slack/tests.py, allauth/socialaccount/providers/slack/urls.py, allauth/socialaccount/providers/slack/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, example/example/settings.py, test_settings.py
This adds a Slack provider which is based on the [OAuth](https://api.slack.com/docs/sign-in-with-slack) service which Slack exposes.
By default, it only requires enough scopes to authenticate the user and get some basic profile information.
=> Add Slack OAuth provider

docs/configuration.rst
Closes #1414
Adds details from #1414 and additional resource to ACCOUNT_CONFIRM_EMAIL_ON_GET and ACCOUNT_LOGOUT_ON_GET.
=> Docs clarification around using GET for Email Confirm and Log Out

allauth/account/adapter.py, allauth/account/forms.py
I've been forking django-allauth for a couple years mainly for these changes, and I think this makes the clean_email function a lot more dynamic and fits its purpose better.
Moving the app_settings.UNIQUE_EMAIL check to the adapter seems to make more sense, while removing the hook from the password reset and add email forms, because the password reset form shouldn't share a validating hook with the signup form, and the add email form already does all the necessary checks it needs to do before allowing it.
My use case for this is I allow "newsletter only" user accounts, which is essentially a User without a username and password set, and have it subscribe to a mailing list. When that same person decides to create a normal user account (normal signup), it need to check if the email exists, …
=> Allow more dynamic email cleaning

allauth/socialaccount/providers/twitter/provider.py, allauth/socialaccount/providers/twitter/views.py
If QUERY_EMAIL is set, append `?include_email=true` to twitter user profile url
To make this work, you need to have email access in your twitter app. See https://dev.twitter.com/rest/reference/get/account/verify_credentials.
NOTE: If user doesn't have an email address in Twitter, email field in response will be a blank string `""` (not None!). I'm not sure how this is typically handled in allauth, seems it will just ask the user to input an email after social auth. Let me know if this needs to be better handled.
Do you need me to add tests for this?
=> Added email to Twitter provider. Closes #1342

allauth/account/models.py, allauth/account/signals.py, allauth/account/views.py
Here are some details.
1. account/signals.py:    revise email_confirmed and email_confirmation_sent
2. account/models.py:   add request and signup parameters to email_confirmation_sent
3. account/views.py:      add the ImmediateHttpResponse exception for form_valid function in SignupView
Hi @pennersr, see if there is something missing or misunderstanding. Thanks.
=> fix account signals

allauth/socialaccount/providers/google/provider.py
Setting prompt=consent during google authentication does not cause a reauthentication prompt to appear; instead, it presents an "allow offline access" consent form.  Furthermore, setting access_type=offline interferes with the provider configuration value google.AUTH_PARAMS.access_type
Setting prompt=select_account, however, will display a screen in which the user can actually select the user identity with which to log in (even if the user is not using multiple Google accounts, they are still presented with a selection).
While not as good as clearing the google auth cookie entirely, this at least is closer to the spirit of reauthentication, and more intuitive to the user.
=> Force reauthentication by Google, not merely presentation of offline-access consent screen

docs/providers.rst
This PR adds setup instructions for the Dropbox provider to the documentation.
In addition, the changes make the majority of the setup instructions more uniform, and fixes some markup flaws.
=> Add Dropbox setup information to documentation

allauth/socialaccount/providers/facebook/views.py
With this change, you can change Facebook auth url to https://m.facebook.com/dialog/oauth when you need to force using mobile auth page.
=> Added settings for changing Facebook auth url

allauth/locale/fr/LC_MESSAGES/django.po
Strings were not taken into account in fr installs because they were fuzzy.
Fixed some bad/incomplete translations.
=> Fixed fuzzy strings in fr

allauth/socialaccount/providers/github/views.py
If the Github email request fails the `emails` variable will be a dictionary containing error info. This dictionary has content and is thus considered as `True`, but it does not actually contain an email at index 0. 
This happens for instance with a 404, when no emails can be read. This fixes https://github.com/pennersr/django-allauth/issues/1234 when the scope is not set up to read private emails.
=> Check status code of Github emails response

allauth/socialaccount/providers/battlenet/tests.py, allauth/socialaccount/providers/battlenet/views.py
This makes the provider more robust by ensuring `id` is present in the returned dictionary. It also properly handles API errors.
=> battlenet: Add error checking in Battle.net output

allauth/socialaccount/providers/battlenet/tests.py, allauth/socialaccount/providers/battlenet/views.py, allauth/socialaccount/providers/slack/views.py
Because the China region uses a different user database, it is critical
to store the API region that was used for the user's creation.
--
This is a commit made in preparation for concurrent multi-region support in the Battle.net API.
Here is the problem: There are two installations of the Battle.net API: one on battle.net and another on battlenet.com.cn. As you can see from the adapter, the URLs are different depending on the API used.
However, I *could not confirm* whether the UIDs we are currently extracting (the `id` field from the data returned) are unique worldwide or per-installation. Same for the Battletag (username). I strongly suspect they are not, which means the UID extraction cannot currently non-china + china at the same time.
*However*, we cannot simply append the region to …
=> battlenet: Make the Battle.net region available in `extra_data`

allauth/socialaccount/providers/oauth2/client.py
Bug: The header is not propagated from adapter to client Oauth2
result: reddit reponse 429 too many request.
https://www.reddit.com/r/redditdev/comments/3qbll8/429_too_many_requests/
=> Fix: Header not propagated from adapater to client

allauth/socialaccount/providers/__init__.py
changed provider_map from dict to OrderedDict to ensure ordering when calling as_choices().
fixes issue #1336
=> fixed unwanted migrations from socialaccount

AUTHORS, allauth/socialaccount/providers/fivehundredpx/provider.py, allauth/socialaccount/providers/fivehundredpx/tests.py, allauth/socialaccount/providers/fivehundredpx/urls.py, allauth/socialaccount/providers/fivehundredpx/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
Adds authentication for [500px.com](https://500px.com/)
Documentation for this Oauth1 API: https://github.com/500px/api-documentation
I have tested this locally and it seems to work as expected.
=> Add 500px oauth integration

allauth/socialaccount/providers/reddit/views.py, docs/providers.rst
See the [Reddit API rules](https://github.com/reddit/reddit/wiki/API#rules)
> Change your client's User-Agent string to something unique and descriptive, including the target platform, a unique application identifier, a version string, and your username as contact information, in the following format: `<platform>:<app ID>:<version string> (by /u/<reddit username>)`
> - Example: `User-Agent: android:com.example.myredditapp:v1.2.3 (by /u/kemitche)`
> - Many default User-Agents (like "Python/urllib" or "Java") are drastically limited to encourage unique and descriptive user-agent strings.
> - Including the version number and updating it as you build your application allows us to safely block old buggy/broken versions of your app.
> - NEVER lie about your user-agent. This includes spoofing …
=> Allow custom user agent for Reddit auth.

allauth/socialaccount/providers/reddit/provider.py
On `/accounts/social/connections/`, it changes from saying "Reddit Reddit" to "Reddit yourusername"
=> Use friendlier name for RedditAccount to_str method

allauth/socialaccount/templatetags/socialaccount.py
See https://docs.djangoproject.com/en/1.9/releases/1.9/#assignment-tag
Introduces a compatibility layer for template.Library().assignment_tag()
to use simple_tag() in Django >= 1.9
=> assignment_tag is deprecated

allauth/socialaccount/migrations/0001_initial.py
Hi,
I made a pull request to address the issue: #1539. The issue arises when adding allauth for the first time and running migrate on a new MySQL utf8mb4 schema. I had to manually fix the migration file to make the django `python manage.py migrate` command work. The fixed second migration you wrote did not fix the issue as the 0001_initial migration runs first and fails. This was tested on Django 1.10.3.
Thanks,
Arjun
=> Fixed Migration 0001_initial to work for new project migrations

allauth/account/utils.py
exists() is more efficient when we don't need the exact number of matching rows.
=> Use qs.exists() instead of qs.count() == 0

ChangeLog.rst, allauth/socialaccount/providers/battlenet/provider.py, allauth/socialaccount/providers/battlenet/validators.py, allauth/socialaccount/providers/battlenet/views.py, allauth/socialaccount/providers/oauth2/views.py, docs/providers.rst
Alrighty, now that 8dc2f2d5cc3ce0e5e1b999129ceaa57ed4e75390 has landed I can go ahead with this :)
The first commit starts addressing #1442. It doesn't outright *remove* the adapter but it makes it way less nasty. The current adapter *always* causes the "user", "user1"... mechanism because the battletag is never saved. Additionally, the current adapter always forces at least two sql writes (first the user, then re-saves the user's battletag).
So we first allow overriding the `username_regex` attribute. Rather than make it a setting, we allow specifying it in the adapter, which I believe to be a reasonable solution.
With that done, we can change the Battle.net adapter to use that and get the battletag as the username data.
The next commits address the china issue:
- `valid_region` is …
=> Assorted improvements to the Battle.net backend

docs/advanced.rst
This adds documentation as suggested in #1544. I was unsure of where to add this so chose to do it in the "Advanced" page.
I'm open to suggestions on how to improve this!
=> Add docs about protecting Django admin via allauth.

allauth/account/app_settings.py
This is important for things that walk public properties (freezegun in my case)
=> Don't access username field if USER_MODEL_USERNAME_FIELD is None.

docs/providers.rst
does not match name (OAUTH_ENDPOINT -> PROFILE_ENDPOINT)
=> Fix providers.rst - Firefox Accounts PROFILE_ENDPOINT typing error

docs/showcase.rst
I shut down hopper.pw a while ago, so it should be removed from this list.
=> remove hopper.pw from list of examples

docs/providers.rst
Configuring the GitHub OAuth correctly in order to be allowed to do actual things via GitHub v3 API  [is obviously a challenge](http://stackoverflow.com/questions/6802516/github-api-create-repo/39727575). This addition to the docs should remediate this problem for django-allauth users.
=> [Docs] Add scope configuration details for GitHub

allauth/account/forms.py, allauth/account/utils.py, allauth/compat.py, allauth/socialaccount/providers/__init__.py, allauth/socialaccount/providers/google/tests.py, allauth/urls.py, allauth/utils.py
Also, @pennersr any thoughts on dropping Django 1.7 compatibility? It's no longer supported upstream, and Django 1.9 support ends in April.
=> Drop Django 1.4/Python 2.6 compatibility hacks

allauth/socialaccount/providers/openid/provider.py, allauth/socialaccount/providers/openid/tests.py, allauth/socialaccount/providers/openid/views.py, docs/providers.rst
This commit adds possibility to specify data you want to request from openid provider. The returned data will be stored in extra_data attribute of socialaccount.
=> Added support for requesting extra_data from OpenId servers

.travis.yml
Adds a webhook configuration to the Travis config to trigger building [the latest docs](https://django-allauth.readthedocs.io/en/latest/) on ReadTheDocs.org.
This should work out-of-the-box. If not please check the [docs configuration on RTD](https://readthedocs.org/dashboard/django-allauth/version/latest/).
Background Reading
-------------------
- http://read-the-docs.readthedocs.io/en/latest/webhooks.html#others
- https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications
Addresses https://github.com/pennersr/django-allauth/pull/1609#issuecomment-279645264.
=> Build latest docs automatically on RTD for successful builds

allauth/locale/fr/LC_MESSAGES/django.po
There's a spurious character at the end of that sentence, it should not exist.
=> French translation: fix superflous char

docs/configuration.rst
I believe this was a case of forgetting to update the docs. 
But i discovered that the correct variable to redirect logged in users from the default `/accounts/profile` url is `LOGIN_REDIRECT_URL` not `ACCOUNT_LOGIN_REDIRECT_URL` as stated in the docs.
Also thanks for this great library. It's a Life saver and would always be a life saver for authentication in django apps 👍
=> LOGIN_REDIRECT_URL not ACCOUNT_REDIRECT_URL

allauth/socialaccount/providers/bitbucket_oauth2/provider.py
It looks like `username` was (intentionally or) unintentionally left out in the extraction of common fields. Interestingly, this fields is extracted in both the [Bitbucket implementation](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/bitbucket/provider.py#L30) and the two major competitors GitHub and GitLab. The `username` field is actually populated in the `extra_data` for Bitbucket_OAuth2, so this probably has been overlooked in the past only.
This PR adds the missing `username` field extraction, and aligns the keyword argument order with the 3 other social account provider implementations, `GitHubProvider`, `GitLabProvider` and `BitbucketProvider`.
=> [Bitbucket OAuth2] Extract username for common fields

allauth/account/app_settings.py
This fixes a bug when setting USERNAME_VALIDATORS.
USERNAME_VALIDATORS is a list of paths which fails when passed to import_attribute() - so instead pass each path in the list to import_attribute().
=> handle validators being a list

allauth/templates/account/email/email_confirmation_message.txt, allauth/templates/account/email/password_reset_key_message.txt
Based on my limited UX testing, it seems that users don't read the confirmation and password reset emails. No surprise there. They just try to click the first link they see.
Because the first link they see is the domain name, I have seen them try to click that link, only to be confused that the email confirmation apparently did not work.
This commit makes the first (and biggest) link the confirmation link. Later on in the email, the site domain is displayed.
I realise that developers can override these templates, but why not make the UX a little bit nicer by default?
=> UX improvement: Remove first mention of domain name in emails

docs/installation.rst, docs/views.rst
This includes two commits:
- It documents in `installation.rst` whether `django.contrib.auth` is required, and whether the URLs provided by that package are required. It mentions the URL names provided by allauth
- It documents in `views.rst` the URL names of the views.
=> Document provided URL names, and compare with django.contrib.auth.urls

allauth/socialaccount/helpers.py, allauth/socialaccount/signals.py
The new signal `social_account_updated` fires when a social login
`connect` flow is completed but the social account already exists
for the currently authenticated user. This allows customization
of how this scenario is handled.
=> Add a signal for social account updates

allauth/account/views.py
It was not possible to add site logo in confirm_email url, including site object in ctx makes this work
=> Add site to context

README.rst, docs/advanced.rst, docs/configuration.rst, docs/decorators.rst, docs/faq.rst, docs/installation.rst, docs/providers.rst, docs/signals.rst, docs/templates.rst, docs/views.rst
Unlike Markdown, you should surround code literals with double backticks
on either side, ``like this``. This goes through all the .rst files and corrects this.
=> Form code literals in RST docs correctly

allauth/account/views.py
Use self.success_url in HttpResponseRedirect instead of hardcoded reverse('account_email'). For inheritance purposes.
=> Update post method in EmailView

allauth/socialaccount/providers/vk/views.py
user_id isn't required in request to api: https://vk.com/dev/users.get
but gets exception if it aren't set: https://github.com/pennersr/django-allauth/issues/1691
=> user_id isn't required in request but gets exception if it aren't set

allauth/locale/pt_BR/LC_MESSAGES/django.po
Replaced 'Cadatre' with 'Cadastre-se'
=> Fixed typo in pt_BR/LC_MESSAGES/django.po

allauth/socialaccount/providers/kakao/provider.py
I added a simple feature that gets original profile image from KAKAO API.
The original version of django-allauth's kakao provider only supports the function to get thumbnail profile image.
=> Alter get_avatar_url for getting a profile_image(full-size image) on Kakao provider

allauth/socialaccount/providers/shopify/provider.py, allauth/socialaccount/providers/shopify/tests.py, allauth/socialaccount/providers/shopify/views.py, docs/providers.rst
This an optional feature that allows an all-auth site to tie the actual token, email, first and last of the Shopify user to the all-auth account, rather than the shop's token and email. 
As noted in code comments before this change, the extra_data for the user can not be obtained from an API request. However it can now be obtained by utilizing 'online' as an access_mode. This causes shopify to provide the user's details when passing back the auth token (and gives a token with a ~24hr expiration).
See Also: https://help.shopify.com/api/getting-started/authentication/oauth#api-access-modes
The code is entirely based off whether or not the 'associated_user' is given to us by Shopify. Which will be true if they put in the existing AUTH_PARAM setting. I thought this more explicit then adding a …
=> Support for Shopify per-user access mode

allauth/account/app_settings.py, allauth/account/managers.py, allauth/account/utils.py, docs/configuration.rst
- First commit makes the email confirmation cooldown period available in the settings, because it really should be.
- Second commit fixes a potential albeit rare crash due to the race condition between the try and except block.
=> Fixes to EmailAddress

AUTHORS, allauth/socialaccount/providers/patreon/provider.py, allauth/socialaccount/providers/patreon/test.py, allauth/socialaccount/providers/patreon/urls.py, allauth/socialaccount/providers/patreon/views.py, docs/overview.rst, docs/providers.rst, test_settings.py
Adds Patreon Oauth2 provider.  We're about to use this at New Atlas (newatlas.com), all working as expected for me here.
https://www.patreon.com/platform/documentation/oauth
=> Adds Patreon Provider

docs/views.rst
In password management the url for password change is `account_change_password`, not `account_inactive`
=> Fixed error in documentation's views section

allauth/locale/ko/LC_MESSAGES/django.po
Not `쇼설`. Should be `소설` for consistency.
=> [Korean] Fix typo

allauth/socialaccount/providers/kakao/views.py
Kakao now supports `client_secret`.
so we don't need to have `client.consumer_secret = None` anymore.
=> Kakao can use client_secret now

allauth/account/tests.py, allauth/account/views.py
Django 1.11+ prevents password tokens from being leaked through the
HTTP Referer header if a template calls out to third-party resources
(i.e., JS or CSS) by setting token in session and redirecting.
Fixes #1755
=> Fixed potentional security issue with leaked password tokens

docs/signals.rst
Added missing `request` argument for `email_confirmed` and `email_confirmation_sent`signals.
=> Update signals docs

.gitignore, tox.ini
Due to the lack of a `package.json` and `node_modules` directory on the
repo, npm could install standard in another directory than
`node_modules/bin/`, which means the standardjs doesn't start.
This PR fixes this behavior.
If a package.json file is added, the mkdir instruction from tox.ini can be
deleted.
=> Fix testenv standardjs

allauth/account/adapter.py, allauth/account/signals.py, allauth/account/tests.py
Changes the behavior of allauth' user_logged_out signal to the same as [django' one](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.signals.user_logged_out). To perform this, django' signal is forwarded as allauth' one if the logout comes from the allauth' logout view (to be precise, from logout method of the default AccountAdapter).
It also corrects unexpected test failures when tests are run from a fresh copy of the repo.
Fixes #1787.
=> Fix user_logged_out signal behavior

docs/providers.rst
The names mentioned do no longer match names in LinkedIn developer backend.
Further more, Oauth 2, will not work without explicit redirect URI's and
the documentation is misleading.
Up to 200 redirect URI's can be specified per application, so
development URI's are no issue and non-existing domains or only locally
resolvable domains are accepted (tested).
Reworded the Oauth 1 bit, but no testing has been done on my part to verify if
empty callbacks are still accepted.
=> Update information to match dev page

docs/configuration.rst
Current wording says
> A path to a list of custom username validators.
But it doesn't say it should be a list of callables. I got a `TypeError` when I tried the following:
```py
custom_username_validators = ['django.contrib.auth.validators.ASCIIUsernameValidator']
```
I eventually found out the correct usage in https://github.com/pennersr/django-allauth/blob/04928b121e55aad0db6ed422e32ddc8bda997be2/allauth/account/tests.py#L41-L45 but I thought it would be better to add an example to the documentation.
=> Add an example for ACCOUNT_USERNAME_VALIDATORS

allauth/socialaccount/providers/twitch/provider.py, docs/providers.rst
Without user_read, the default authentication causes a confusing 401.
Also update wording for persona documentation.
=> twitch: Add user_read as default scope

allauth/socialaccount/providers/facebook/provider.py, docs/providers.rst
As of October 7th, 2017, currently used default Facebook Graph API v2.4 will reach its end of life.
=> Update default Facebook Graph API version to v2.5

docs/providers.rst
I just spent like 20 minutes digging through the codebase to figure out how to make GitLab login work, hopefully others won't have to do the same 🙃
=> docs: Document required read_user scope for GitLab

allauth/socialaccount/providers/windowslive/views.py
it was caused due to 400 response not being raised
=> fix: windowslive breaking with invalid token

docs/providers.rst
Make the location of the secret key explicit. Addresses #1870.
=> Better documentation for Stripe configuration

allauth/socialaccount/providers/stripe/provider.py
Better stringification for Stripe accounts, using the 'business_name'
key in extra_data. Addresses #1871.
=> ADD StripeAccount.to_str

allauth/locale/fr/LC_MESSAGES/django.po
The translation of "password" was used in place of "email".
=> Fixed a typo error in French Localization.

docs/configuration.rst
This setting was added in #1387 but documentation for it was missing.
=> docs: document the `ACCOUNT_EMAIL_MAX_LENGTH` setting

allauth/socialaccount/providers/vk/provider.py
Apparently, now vk doesn't return profile url with json, so now it should be generated from uid.
=> Fixed vk profile url

allauth/socialaccount/providers/vk/views.py
Exception KeyError: 'response'
without this patch
=>  API version is required param now

allauth/socialaccount/providers/linkedin_oauth2/views.py
Similar to https://github.com/pennersr/django-allauth/commit/8705514dc164577f801cdacb5c46623c8cb9909b but for LinkedIn
- If LinkedIn responds with  a 401 in case of an invalid token,
raise an `HTTPError` (resp.raise_for_status) to handle the
exception correctly instead of the current Http500 status
because of a `KeyError`.
=> Use HTTP response code provided by LinkedIn

allauth/socialaccount/providers/google/provider.py, docs/providers.rst
Google ordinarily only provides a refresh token the first time you connect a Google account. For `offline` access apps, you can also receive a new refresh token if you pass the `consent` auth param.
This param adds the `consent` param in addition to the current `select_account` param (which lets you access the Account Switcher for choosing which Google account).
See also:
* https://github.com/pennersr/django-allauth/pull/1303
* https://github.com/pennersr/django-allauth/pull/1376
=> Fixes Google Provider re-authentication to successfully receive new refresh token

AUTHORS, allauth/socialaccount/providers/orcid/provider.py, allauth/socialaccount/providers/orcid/tests.py, allauth/socialaccount/providers/orcid/views.py
ORCID v1.2 API will be shut down in a few days (https://groups.google.com/forum/#!topic/orcid-api-users/V_cPqOQ9QIs). This migrates the ORCID provider to the newest version of their API (v2.1).
=> Update ORCID to v2.1 API

allauth/socialaccount/providers/eventbrite/provider.py, allauth/socialaccount/providers/eventbrite/tests.py
had a typo
`data.get("email") ==> data.get("emails")`
=> Issue 1968 social account event brite does not work

allauth/socialaccount/providers/quickbooks/provider.py, allauth/socialaccount/providers/quickbooks/test.py, allauth/socialaccount/providers/quickbooks/urls.py, allauth/socialaccount/providers/quickbooks/views.py, docs/overview.rst, docs/providers.rst, test_settings.py, tox.ini
This is a custom provider I wrote to do oauth2 auth with Intuit Quickbooks and Payments APIs. 
It requires that you set a QBO_TEST variable in your settings file. If it's true, it uses the sandbox URL. If not, it assume production and tries that URL. In my system this file is at config.settings.base, probably need help making that more generic. But it works.
=> Quickbooks custom Provider

allauth/locale/de/LC_MESSAGES/django.po
The German wording for "you must enter the same email twice" was "you must enter the same password twice", which can be really confusing for users.
This should probably be fixed on Transifex as well, but my request to join the de team on Transifex has not been answered yet.
=> Fix a serious error in German translation

ChangeLog.rst
Version 0.35.0 dropped support for Django versions before 1.11 (1.8 and 1.10), and added explicit support for Django 2.0. Fixes #1944.
=> Note Django support changes in 0.35.0

AUTHORS, ChangeLog.rst, allauth/account/tests.py, allauth/account/utils.py, tox.ini
Prior to this fix, a user that used a UUIDField primary key would not be logged in due to the failing comparison of user pk with the "stashed" pk.
=> Bugfix: UUIDField pk - allow confirm email login

AUTHORS, allauth/socialaccount/providers/cern/provider.py, allauth/socialaccount/providers/cern/tests.py, allauth/socialaccount/providers/cern/urls.py, allauth/socialaccount/providers/cern/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
This PR adds [CERN](https://home.cern/) OAuth2 support. 
It is already being actively used by physicists around the world in a CERN project I am working on.
Merging this into the django-allauth repository would enable other developers at CERN to easily integrate CERN single sign-on in their projects.
=> Add CERN OAuth2 provider

allauth/socialaccount/providers/auth0/provider.py, allauth/socialaccount/providers/auth0/tests.py, allauth/socialaccount/providers/auth0/views.py
Now Auth0 clients are OIDC compliant by default, so the response from `/userinfo` endpoint and the `id_token` includes only the [OpenID connect standard claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).
Setting the default scopes *openid*, *profile* and *email* the user profile always will be OIDC compliant regardless if `OIDC conformant` is disabled in the client settings.
=> fix(Auth0): Support OIDC conformant clients as well

allauth/socialaccount/providers/baidu/provider.py
Old: The function always return fixed url `https://openapi.baidu.com//rest/2.0/passport/users/getLoggedInUser`. This is not the correct url point to user's profile page.
New: `https://www.baidu.com/p/<uname>/` Is the correct user's profile page. Like https://www.baidu.com/p/seieewkx.
=> fix(baidu): Fixed baidu's get_profile_url bug.

allauth/socialaccount/providers/openid/views.py
As described in issue #2072, Yahoo OpenID fails if the 'next' parameter is blank / not specified.  This PR makes it so the next parameter is not passed along unless it was set.
=> fix: how OpenID specifies 'next' in redirect URL

allauth/socialaccount/providers/openid/views.py
Using the URI of `/` based on the current request makes it impossible to auth across multiple subdomains.
This allows the admin to override the OpenID realm in their `settings`.
=> feat(openid): Support specifying the realm in settings

ChangeLog.rst, allauth/socialaccount/providers/openid/views.py, allauth/socialaccount/providers/steam/provider.py, allauth/socialaccount/providers/steam/urls.py, allauth/socialaccount/providers/steam/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
This took me a while! I wanted to implement a Steam provider. Steam is OpenID, but gives no access to even the most basic things (no username!). That's all behind a custom API which requires its own key.
To implement Steam, I wanted to do this right, but there were no other instances of a custom OpenID-based provider.
More specifically, to avoid code duplication, I had to reimplement the OpenID login and callback views into class-based views. They are now much more extensible and I make heavy use of that in the Steam provider.
Tested in production.
=> OpenID refactor to make way for a Steam provider

docs/forms.rst
I wrote the forms.rst documentation file a while back, I noticed it messed up the menu on readthedocs, this pr matches the same heading style that templates.rst uses which will also fix the sidebar menu on readthedocs.
=> Fixed headings used on forms.rst docs to match menu style

allauth/socialaccount/providers/kakao/provider.py
In kakaoprovider, the key name of the extra common fields is 'nickname'. This looks a bit strange.
=> Change kakao's extra common field name from 'nickname' to 'username'

docs/faq.rst
on readthedocs a quote block will have any quotes (') substituted with apostrophes. Make quote block a codeblock to preserve quotes.
=> Place code in code block to preserve quotes

AUTHORS, docs/forms.rst
Just some small touch-ups!
- Use proper single quotes in code sample
- Add apostrophes to possessives
- Consistently use periods at the end of sentences
- Use code formatting when referring to `save` method
=> Documentation improvements on Forms page

allauth/socialaccount/providers/battlenet/views.py, docs/providers.rst
The Battle.net provider URLs have [recently changed][1]. Users will have to update their API keys by creating an application in the new [Battle.net developer portal][2].
With regards to release planning, the old endpoints will be turned off on January 6th. In addition the new endpoints require new API keys to be obtained, but all user ids will still be applicable.
This touched  #2125 in so far that it just updates the URLs instead of provisioning a fully new provider.
[1]: https://develop.battle.net/documentation/guides/migration-guide
[2]: https://develop.battle.net/
~~In case you add a new provider:~~
=> fix(battlenet): Update provider urls

.travis.yml
This is good in general (more recent), and likely to fix builds with
Django 2.2, which currently fail:
> django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is
> required (found 3.8.2).
=> chore: ci: Travis: use dist=xenial

allauth/socialaccount/providers/discord/provider.py
Discord performs email verification, and indicates this in the extra data returned by their OAuth2 API. 
[Discord API documentation](https://discordapp.com/developers/docs/resources/user#user-object): 
I also tested this by looking at the API data returned for my own already-verified account, and looking at the API data returned for a new test account that I created with an email address entered but not verified. As you can see in the screenshot below, you are unable to add a phone number to the account or enable 2FA until after your email has been verified. 
The `extract_email_addresses` code is copied from the `google` adapter and modified just to change which key to `get` from the `data`.
=> feat(discord): Added verified email detection for Discord provider

allauth/locale/pt_BR/LC_MESSAGES/django.po
Missing a letter in `registado` (should be `registrado`) at .po file
=> Edit a small typo on pt_BR locale

AUTHORS, allauth/socialaccount/providers/slack/provider.py, allauth/socialaccount/providers/slack/views.py
Using `users.identity` includes full user details rather than partial provided by `auth.test`
=> fix(slack): Use proper identity endpoint

allauth/socialaccount/providers/trello/provider.py, allauth/socialaccount/providers/trello/views.py
Add `extract_common_fields` to `TrelloProvider` to properly retrieve email (if available). Change Trello API endpoint to retrieve user email and not just member id. Requires "read,account" scope for Trello to get email (see below).
By default uses `get_default_scope()` that was already provided but was unused in TrelloProvider.  Allows overriding in settings e.g.
```
SOCIALACCOUNT_PROVIDERS = {
'trello': {
'SCOPE': 'read,account',
},
}
```
=> TrelloProvider fixes

ChangeLog.rst, allauth/socialaccount/providers/globus/provider.py
Globus provider's `uid` was resolving to `None` which caused problems in my application. I've updated the `extract_uid` method to properly obtain the field `sub` (a requirement of all OpenConnect providers) and verified that this resolves the problem.
---
=> fix(globus): Fixed extract_uid

allauth/account/forms.py
When `user.email` equals `None` they're not able to reset their password because of a bug in `EmailAwarePasswordResetTokenGenerator`. This tiny PR fixes it.
People still able to reset their password even if they don't have an email address on django's `user`, but they have it on django allauth's `EmailsAddress`
[Commit](https://github.com/pennersr/django-allauth/commit/3fe584e1a3998e244e608d097ca4fececa77aa30#diff-3b9310d6e2c9a729f9c65c16647b3e1aR47) where the issue was introduced
Thanks
=> Handle user.email=None case when generating password token

allauth/socialaccount/models.py
This is a tiny commit. Changing `SocialLogin()` to `cls()` gives more flexibility to the code. For example, if I want to inherit `SocialLogin` class, (which indeed is my use case) I should copy-and-paste `deserialize()` function and manually change `ret = SocialLogin()` part for the new subclass in order to obtain the desired class instance.
=> chore(socialaccount): use cls in class method

AUTHORS, allauth/socialaccount/providers/battlenet/views.py, docs/providers.rst
Added:
- Provider setting to specify default Region. This is more convenient than setting the query parameter every time, which is prone to user error. The preference now is; query parameter (unchanged) > setting (added) > default fallback (unchanged)
- Added documentation for the Battle.net provider for this new setting.
- Also documented available scopes while I was at it, since that wasn't explicitly documented yet.
Rationale:
For a lot of use cases, the Battle.net API will only be used by users from primarily a single region (for example, a website for a World of Warcraft guild), setting a default would be convenient for such applications. The query parameter is useful, but one must take care to make sure its uniformly specified everywhere the link is placed.
More sensible is to …
=> feat(battlenet): added Region parameter to provider settings

allauth/socialaccount/providers/orcid/provider.py
When using the orcid provider to signup a user, the email wasn't been extracted as expected (the signup form was showing always the email field empty).
=> fix(orcid): update email extraction path

AUTHORS, allauth/socialaccount/providers/sharefile/provider.py, allauth/socialaccount/providers/sharefile/tests.py, allauth/socialaccount/providers/sharefile/urls.py, allauth/socialaccount/providers/sharefile/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
This adds a ShareFIle (https://www.sharefile.com/) Oauth2 provider.   We are currently using this in our app.  Was a pretty painless addition but let me know if there is something more needed to get this merged. 
Thanks for such a great library! 
=> feat(socialaccount) Add Sharefile provider

.travis.yml, tox.ini
Also uses `ignore_errors = True` to keep going on errors, but still exit
non-zero if one command fails.
=> chore(tox): rename flake8 to checkqa

allauth/socialaccount/providers/vk/provider.py, allauth/socialaccount/providers/vk/tests.py, allauth/socialaccount/providers/vk/views.py
VK API v3 got deprecated. Details: https://vk.com/dev/version_update_2.0
There could be some changes around extra fields, this just bumps version to latest, and makes sure login works
=> fix(vk): Bump VK API version to 5.95

allauth/locale/de/LC_MESSAGES/django.po
Although it was technically correct I'd like to change the
capitalization of personal pronouns, for three reasons:
- It is consistent now, all personal pronouns are capitalized the same way.
- The uppercase capitalization is acceptable for written literature, which
this project isn't.
- The uppercase capitalization is used by very old people, which are probably not
the target demographic of most of the projects using allauth
=> fix(translation): German spelling of personal pronouns

allauth/urls.py
This is useful to reuse them without the other urlpatterns.
=> Add allauth.urls.provider_urlpatterns

allauth/socialaccount/providers/base.py, allauth/socialaccount/providers/facebook/provider.py, allauth/socialaccount/providers/facebook/static/facebook/js/fbconnect.js
Added the ability to override default permission scopes as well as declare the `rerequest` auth type for Facebook.
The scope override is needed in the case that you want to request additional permissions beyond those you originally requested (i.e. those defined in `SOCIALACCOUNT_PROVIDERS`) as well as in the case that you want to re-request a permission the user previously declined, in which case you also need to be able to set the `auth_type` to `rerequest` (see [Re-asking for Declined Permissions](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#reaskperms) in the Facebook Login docs).
I'm happy to also update the docs and tests for this change but wanted to see if there was any feedback before doing so.
=> feat(socialaccount): Add Facebook additional scope (re)requesting

allauth/socialaccount/providers/gitlab/provider.py, docs/providers.rst
This permit to handle gitlab as easily as the other providers.
By default, if no scope is provided, it default to use 'api',
which seems overkill for simple authentication.
=> feat(gitlab): Set the default scope to read_user

allauth/templates/account/email/email_confirmation_message.txt, allauth/templates/account/email/password_reset_key_message.txt
This affects, for example, site names containing "&".
=> fix(templates): Don't HTML-escape plain text emails

allauth/locale/nl/LC_MESSAGES/django.po
Update `locale/nl` to include correct translation for too many login attempts.
=> fix(locale/nl): correct too many login attempts message

setup.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

AUTHORS, allauth/account/views.py
Currently, if the ChangePasswordView has an uncaught exception, the value of the "oldpassword" form field will not be sanitized when it appears in error reporting logs/emails generated by Django (when `DEBUG` is False). This is obviously not ideal because the value of this form field is meant to contain the current password for a given user.
You can reproduce this in a default django/django-allauth installation by authenticating with a user, visiting /account/password/change, logging out of that users session while leaving the form open (say, logging out in a different browser tab), and then submitting the form. The resulting email report generated by Django will contain the unsanitized value of the "oldpassword" form field.
This commit adds "oldpassword" (which appears in the account …
=> fix(account): Prevent "oldpassword" POST parameter from leaking

allauth/socialaccount/providers/openid/provider.py, allauth/socialaccount/providers/openid/views.py, docs/providers.rst
There are OpenID providers (eg. Steam) which have known problems with stateful operation.
This PR adds a "stateless" flag on an OpenID provider which forces stateless operation.
=> Allow forcing stateless operation for an OpenID provider

docs/providers.rst
Silly typo: for Patreon should be "patreon", not "paypal". 💯
=> Change SOCIALACCOUNT_PROVIDERS for Patreon

AUTHORS, ChangeLog.rst, allauth/socialaccount/providers/twitch/provider.py
This PR fixes an issue with the Twitch provider where it fails to return a profile picture for accounts registered after version 0.40.0.
=> fix(twitch): Retrieve correct profile image

.travis.yml, AUTHORS, tox.ini
=> Test Django 3.0 & Python 3.8 on Travis

allauth/locale/pl/LC_MESSAGES/django.po
Hi, thanks for great library. I noticed error in polish translations:
_"Primary e-mail address set"_ is translated as _"Ustaw podstawowy adres e-mail."_ 
which means something like 
_"Please set your primary e-mail address."_
I changed it to _"Podstawowy adres e-mail został ustawiony."_  This is similar to 
```
#: templates/account/messages/password_set.txt:2
msgid "Password successfully set."
msgstr "Hasło zostało ustawione."
```
=> fix(i18n): Fixed incorrect translation entry

AUTHORS, allauth/socialaccount/providers/kakao/views.py, allauth/socialaccount/providers/naver/views.py
When requesting oauth provider Naver or Kakao, if there is an error such as incorrect token length, 'resp' generates an error.
However, if you look at the Naver and Kakao views, it will not check this and try to extract `uid` or any data from the response and generate 500 error.
As with other provider views, I think we need the `resp.raise_for_status()` for check error.
thanks :)
=> default raise http error in 'Naver', 'Kakao" social auth provider

allauth/socialaccount/providers/amazon/views.py
Amazon has changed the URL for the profile endpoint. Source: https://developer.amazon.com/docs/login-with-amazon/obtain-customer-profile.html#call-profile-endpoint
This PR updates the profile endpoint URL in `AmazonOAuth2Adapter`.
=> fix(amazon): Fix Amazon API profile url

allauth/socialaccount/providers/github/views.py
- GitHub is deprecating authentication to their API using query params via the `access_token` query param **(UPDATE: latest email notification from GitHub stated that this will officially go away July 1st, 2020)**. An `Authorization: token TOKEN` header should be added to the request instead.
- see also https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
- fixes #2457
=> fix(github): switch to header authorization

allauth/socialaccount/fields.py, allauth/tests.py, allauth/utils.py
I ran into issues with the `deserialize_instance` utility - for custom fields under Django3 it was still calling `from_db_value` with incorrect arguments. Specifically, the `context` parameter was [deprecated in Django 2](https://docs.djangoproject.com/en/2.0/releases/2.0/#context-argument-of-field-from-db-value-and-expression-convert-value) and [removed in Django 3](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0).
The tests didn't reveal this as they define their own custom field and `from_db_value` method which does not vary based on the Django version.
There was some adjustment to the `JSONField` implementation to define a variable `from_db_value` signature based on Django version, but I think it possibly should have hinged on the actual removal of the …
=> Fix `deserialize_instance` in Django 3

AUTHORS, allauth/account/adapter.py
Newer Django versions has `url_has_allowed_host_and_scheme` function as replacement for deprecated`is_safe_url`.
I've added import check to use new one, if it exists and fallback for old one if necessary.
This patch will fix this warning:
```
RemovedInDjango40Warning: django.utils.http.is_safe_url() is deprecated in favor of url_has_allowed_host_and_scheme()
```
=> Fix: use new function, fallback to depricated one

allauth/socialaccount/providers/microsoft/provider.py
Hi, i found a bug when accessing the page {% url 'socialaccount_connections' %} (/social/connections/) it gave me a 'NoneType' object has no attribute 'strip' and the culprit is provider.py. The problem is that this file calls the strip() function on a null value and python being python doesn't like it ;) The solution i found is quite simple, in the provider.py file the MicrosoftGraphAccount class should be updated from this:
`class MicrosoftGraphAccount(ProviderAccount): def to_str(self): name = self.account.extra_data.get('displayName') if name.strip() != '': return name return super(MicrosoftGraphAccount, self).to_str()`
to this:
`class MicrosoftGraphAccount(ProviderAccount): def to_str(self): name = self.account.extra_data.get('displayName') if not name is None: if name.strip() != '': …
=> Fixed 'NoneType' object has no attribute 'strip'

allauth/socialaccount/providers/facebook/provider.py
Explicit is better than implicit. (PEP 20)
- A single-line return statement introduces more clarity when it implements a single intent.
- Using single-letter variable names is discouraged by popular Python code linters.
=> Make return statement more concise

allauth/socialaccount/providers/facebook/provider.py
Assert statements should not be used in production code.
- We should understand asserts as "comments that don't become outdated".
- Optimized Python code will have assert statements stripped out. (Try `python -O script.py`)
The intent of the original code was to ensure a value, hence `if`, and abort by raising an Exception otherwise.
=> Replace assert by RuntimeError

allauth/socialaccount/providers/nextcloud/views.py
It seems this code has never been tested in production? Anyway, thanks for the great allauth package, it makes external authentication a joy!
=> fix: typo which prevents authentication with nextcloud

allauth/socialaccount/providers/vk/provider.py
VK returns user ID in 'id' field, but for some reason allauth takes ID from 'uid' field of extra_data to construct link to profile.
See https://vk.com/dev/objects/user for user object description.
=> fix(vk): Fixed profile url for VK provider

allauth/socialaccount/providers/twitch/tests.py, allauth/socialaccount/providers/twitch/views.py
This PR fixes the Twitch provider's `complete_login` method, which otherwise throws an exception.
Background: [Twitch is changing their API](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916?u=beheh) to require the `Client-ID` for all endpoints, including the profile URL endpoint. This change is going fully into effect on May 11th, and since May 1st Twitch is performing scheduled windows where this is in effect already.
Without this PR the OAuth login does not complete and instead throws the following error:
```
[twitch] Authentication error: 'unknown' (exception=OAuth2Error('Twitch API Error: Unauthorized (Client ID and OAuth token do not match)',))
```
I've tested the PR in my production application and this seems to fix it.
Examples: `"fix(google): …
=> fix(twitch): Add missing client ID header

allauth/socialaccount/providers/discord/views.py
This commit updates the URLs used by the Discord provider to match the new domain `https://discord.com` rather than the old one (`https://discordapp.com`).
The change was [announced](https://github.com/discord/discord-api-docs/issues/1585#issuecomment-623751530) on May 4th and the new domain is live and working right now. Merging can wait until the change is also present in the [Discord OAuth documentation](https://discord.com/developers/docs/topics/oauth2). Apparently it will only be enforced starting November 7th 2020, so there should be plenty of time.
=>  fix(discord): Switch to new API domain 

docs/providers.rst
According to the Facebook [permissions page](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_friends), the `user_friends` scope now requires an app review.
=> Update Facebook scopes allowed without an app review

allauth/socialaccount/providers/instagram/provider.py, allauth/socialaccount/providers/instagram/views.py
This fixes the Instagram provider to work with the new Instagram API as
per the docs at https://developers.facebook.com/docs/instagram-basic-display-api
=> fix(instagram): Updated to use new API

allauth/socialaccount/providers/odnoklassniki/provider.py
Response of users.getCurrentUser doesn't contain 'link' field:
https://apiok.ru/en/dev/methods/rest/users/users.getCurrentUser
=> fix(odnklassniki): Fixed profile url

docs/installation.rst
- square brackets of lists (not round ones),
- `path()` (not `url()`),
- `accounts/` (not `r'^accounts/'`, 
got warning:
> ?: (2_0.W001) Your URL pattern '^accounts/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path()."
=> fix(installation docs): brackets of lists, path(), url pattern

docs/signals.rst
It looked like explanation refers to the following bulleted line, while it belongs to preceding one. 
I don't like bold (seen on Github), hopefully readthedocs' theme will plain it out, but that's .rst
=> fix(signals docs): update readability

ChangeLog.rst, allauth/account/adapter.py, allauth/account/tests.py, allauth/account/views.py
If a user is blocked from logging in and resets their password successfully then remove the block for that user and allow login. Currently the user is denied for the entire duration of the timeout.
Fixes #2463 
=> fix(login): password reset successful clears login attempt limit cache to allow login immediately

allauth/socialaccount/providers/openid/tests.py
Long term solution: phase out OpenID 2.0 support. Current test relies on
Yahoo (dead now) and Hyves (should be long dead, if it isn't, it's
undead).
This fix silences the tests, until someone wants to find a new provider
or mock the discovery, but OpenID itself has moved on to the next shiny
version: OpenID Connect, so it is best to sunset this support.
- [V] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
- [V] All Python code must be 100% pep8 and isort clean.
=> fix(openid): Mark tests as expected failures

docs/providers.rst
I may be lacking some context, but I believe that the provider name is incorrect in the `providers.rst` doc.
As far I as I can tell it should be the same as the `id` in the provider file [1].
[1] https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/battlenet/provider.py#L12
=> docs: Update provider example for Battle.net

allauth/socialaccount/providers/facebook/views.py
ISSUE #2609
https://github.com/pennersr/django-allauth/issues/2609
There is currently an issue when authenticating with Facebook:
- The initial redirect URL that begins the login process incorrectly separates the scopes with a '+' character
- This causes Social Login Failures, as well as an Invalid Scopes Failure
The new Facebook  API v7.0 update requires scopes to be separated by the ',' character
As mentioned by Facebook support in the image below
- This PR sets the scope_delimter class attribute to a "," character in the FacebookOAuth2Adapter class to resolve the issue
=> fix(facebook) added comma delimiter to remove social login failure and invalid scopes when scopes are valid

allauth/socialaccount/providers/openid/forms.py
The current url points to a 404 page. I've searched the same website for a list of known providers to link to and cannot find one that explicitly states possible providers. 
openidexplained.com site does have a list with details and more information.
=> fix: openid form linking to 404 page, link to openidexplained

allauth/socialaccount/providers/figma/provider.py, allauth/socialaccount/providers/figma/tests.py, allauth/socialaccount/providers/figma/urls.py, allauth/socialaccount/providers/figma/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
This PR adds a provider for Figma login: https://www.figma.com/developers/api#authentication
=> feat(socialaccount/providers): Add support for Figma login

allauth/account/forms.py
Was trying to style forms and found that these fields have hardcoded size, while other inputs don't
=> fix(forms): Remove hardcoded size of textinputs

docs/providers.rst
When the user returns from steam having verified their login, if you do not supply the key in the Secret Key field you get 403 forbidden response errors from steam and oauth fails expecting a json response.
#2358
=> fix(docs): steam provider requires key in client id and secret key fields

allauth/socialaccount/providers/keycloak/provider.py
As per the OpenID Connect spec the standard username claim is `preferred_username`.
By default Keycloak confirms to OpenID Connect spec and provides a `preferred_username` claim, but no `username` claim in the profile scope.
ref: https://openid.net/specs/openid-connect-basic-1_0-28.html#StandardClaims
=> fix(keycloak): Use preferred_username claim for username

allauth/account/adapter.py, allauth/account/tests.py, allauth/socialaccount/models.py
`request.is_ajax()` is being depreciated in 4.0. I've updated adapter.is_ajax() i check 3 different sources for possible flags as to being an ajax based request. Namely checking `HTTP_X_REQUESTED_WITH`, `HTTP_ACCEPT` and the requests content_type.
django's `crypto.get_random_string` function has had a limit parameter which has always defaulted to 12 characters in length. As of 4.0 the limit parameter will be required. As such I've updated the only occurrence that was missing a given limit to use the default as set by django.
I was not entirely sure if I should separate these 2 into separate PR's or not. I figured the get_random_string was small enough and in the same type of vein I'm dealing with in this PR.
Resolves #2538
=> Deprecated method request.is_ajax and crypto.get_random_string requires limit

allauth/account/adapter.py
- This adds request as an available context to all items using render_email for emails and add_message for messages
resolves #2186, resolves #2516 
closes #2197 
=> fix(account adapter): render_to_string takes self.request

test_settings.py
I'm finding tests currently take roughly 200s to complete. That can be reduced greatly by decreasing the PBKDF2 iterations using a custom hasher. This is only applied to test_settings.py and should never be used in production.
Standard Iterations: Ran 525 tests in 227.867s
Decrease Iterations: Ran 525 tests in 17.950s
=> test(test_settings): decrease password iterations to increase test speed

allauth/socialaccount/providers/yahoo/provider.py, allauth/socialaccount/providers/yahoo/tests.py, allauth/socialaccount/providers/yahoo/views.py
- Scope `sdps-r` is no longer in use. Now using `profile`, `email`.
- api for profile data also moved
Deprecation information: https://developer.yahoo.com/oauth/social-directory-eol/
=> fix(provider): Yahoo deprecation of scope and profile url.

example/example/settings.py
example site attempts to import local_settings from the wrong path. local_settings.example states to copy it to local_settings.py and if someone does that in the same directory as the example file then the import needs to be `.local_settings` with the dot.
Also reset and moved ALLOWED_HOSTS above import so import can override it properly.
=> chore(example settings): fix import of local_settings from incorrect path

allauth/account/signals.py, allauth/socialaccount/signals.py
With this PR the Django 4.0 deprecation warnings regarding the providing_args= argument of the signals are removed.
=> fix(signals): Remove Django 4.0 deprecation warning

allauth/socialaccount/providers/stocktwits/views.py
Correcting the scope delimiter used on stocktwits
=> fix(provider): stocktwits scope delimiter is comma not space

docs/forms.rst
Tiny fix to SOCIALACCOUNT_FORMS documentation, changing 'login' -> 'disconnect'
=> Fixed forms.rst SocialAccount forms dict

docs/configuration.rst, docs/installation.rst, docs/providers.rst
While trying to set up allauth, I could not quickly find out how to configure SOCIALACCOUNT_PROVIDERS. This PR makes things a bit more explicit.
=> Improve docs of SOCIALACCOUNT_PROVIDERS

allauth/account/adapter.py
I think the word is supposed to be valid, not vald.
=> fix(account/adapter): Correct spelling in comment

docs/providers.rst
Current documentation makes no mention of having to select app permissions or the fact that the redirect url requires https.
Also when you click on the client id and secret on yahoos website, it auto highlights the line and when you copy/paste from there it adds 4 spaces to the start of the copied string which needs removing.
=> fix(provider docs): yahoo requires manually selecting permissions and https callback

allauth/socialaccount/providers/oauth2/views.py, docs/providers.rst
Sign in with apple added support for pulling user data from apple's temporary session via get_access_token_data method in both OAuth2 and Apple providers, but then neglected to actually use it in OAuth2 dispatch. 
=> fix(apple): get user data with token

allauth/socialaccount/providers/apple/client.py
Fix Apple sign in error, when use PyJWT >= 2.0.0a1
=> fix(apple): Sign in error when use PyJWT >= 2.0.0a1

allauth/socialaccount/adapter.py, allauth/socialaccount/providers/openid/utils.py
using `if not queryset.exists()` is more efficient than checking `if queryset.count() == 0` [read more](https://django.doctor/advice/C9002)
I found this problem during auditing your codebase. [Read the full report](https://django.doctor/pennersr/django-allauth)
=> Improve the performance of ORM calls

allauth/account/__init__.py, allauth/socialaccount/__init__.py, example/example/demo/__init__.py
https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery
Fix RemovedInDjango41Warning
=> fix(django): default_app_config is deprecated in django 3.2

allauth/account/utils.py
Fixes #2799 
One cannot assume that the default manager for an app's user model is named `objects`.
=> fix(accounts): Don't assume User default manager is objects.

AUTHORS, allauth/socialaccount/providers/slack/views.py
Deprecating usage of token as a query string parameter in Web API requests: Apps created after February 24, 2021 may no longer send tokens as query parameters and must instead use an HTTP authorization header or send the token in an HTTP POST body.
See slack post [here](https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps)
=> Slack provider: Works with Bearer token inside HTTP headers

allauth/account/admin.py
this enables admins to use the Django admin panel to select some email addresses from the table and override their `verified` field to True
=> Add admin action to mark email addresses as verified

allauth/locale/cs/LC_MESSAGES/django.po, allauth/locale/en/LC_MESSAGES/django.po, allauth/locale/fa/LC_MESSAGES/django.po, allauth/locale/hu/LC_MESSAGES/django.po, allauth/locale/ky/LC_MESSAGES/django.po, allauth/locale/lt/LC_MESSAGES/django.po, allauth/locale/nb/LC_MESSAGES/django.po, allauth/locale/pl/LC_MESSAGES/django.po, allauth/locale/ru/LC_MESSAGES/django.po, allauth/locale/sk/LC_MESSAGES/django.po, allauth/locale/uk/LC_MESSAGES/django.po
[Django bugfix #30439](https://code.djangoproject.com/ticket/30439) has cause translations with different plural forms definitions are loaded in a separated catalogue. This means that app translations cannot be overwritten on the project level (in project LOCALE).
This pull request synchronize plural forms with the current Django version https://github.com/django/django/tree/main/django/conf/locale
=> fix: synchronize Gettext plural forms with Django

AUTHORS, allauth/socialaccount/providers/cilogon/provider.py, allauth/socialaccount/providers/cilogon/tests.py, allauth/socialaccount/providers/cilogon/urls.py, allauth/socialaccount/providers/cilogon/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
CILogon is a OAuth2-based federated identity provider for hundreds of universities and research institutions around the world, reaching millions of international researchers, students, and administrative staff.
Note: I used the Google provider as a template.
=> feat(socialaccount): Add CILogon as a provider

ChangeLog.rst, allauth/account/apps.py, allauth/socialaccount/apps.py, example/example/demo/apps.py
Django 3.2 introduces DEFAULT_AUTO_FIELD . If you set this to something other than `'django.db.models.AutoField'`, migrations will need to be generated for allauth's models. This pull request sets `default_auto_field` just for these apps so that no migrations need to be generated.
It also hides warnings on Django 3.2.
Fixes: https://github.com/pennersr/django-allauth/issues/2826
=> Set default_auto_field to 'AutoField'

allauth/locale/da/LC_MESSAGES/django.po
I suggest a few changes to the Danish translation file. 
- The Danish spelling of the English words "e-mail" and "e-mail address" is inconsistent in the current version of the translation file. I suggest the spellings "email" and "emailadresse".    
- I suggest changing "bekræftigelse" (unofficial spelling) to "bekræftelse" (the official spelling).  
- I've corrected a few grammatical errors ("noget email" -> "nogen email").
=> Danish spelling

allauth/socialaccount/providers/reddit/provider.py
Using Reddit's screen name as username instead of first name will allow the sign to skip one more field.
=> fix(accounts): Use Reddit name as username

allauth/socialaccount/providers/weixin/views.py
client_class is configurable now.
WeixinOAuth2ClientMixin.get_client is outdated, use default OAuth2View.get_client.
=> fix(weixin): remove WeixinOAuth2ClientMixin

allauth/socialaccount/providers/keycloak/provider.py
This implements a solution to #2963. For this pull request, I've only made the change to the Keycloak provider but I've tackled it in a way that can be generalised across all providers, which is why I picked `OVERRIDE_NAME` as the variable rather than something like `KEYCLOAK_NAME`. I'm happy to change it, though, if you'd prefer it to specify the provider's name in the variable name.
Simply adding a value for `OVERRIDE_NAME` in the provider's block in `SOCIALACCOUNT_PROVIDERS` causes that value to be used wherever the provider's name is used in the UI.
=> fix(keycloak): Add configuration to override provider name displayed in UI

allauth/socialaccount/providers/amazon/provider.py
fix(amazon): When using 'SCOPE': ["profile:user_id"] the users email address is not returned causing a KeyError
=> fix(amazon): When using 'SCOPE': ["profile:user_id"] the users email address is not returned causing a KeyError

allauth/socialaccount/providers/apple/views.py
allauth/socialaccount/providers/apple/views.py:
Remove the use of `verify=True` when calling `jwt.decode()`, as it is
deprecated with pyjwt == 1.7.0 (see
https://github.com/jpadilla/pyjwt/blob/3f735fdf68cc865a6241aae1fcf92a410c73fbdb/jwt/api_jws.py#L132-L134)
and removed in pywjt == 2.0.0.
The default is now to use an (optional) `options` dict, that always uses
`{"verify_signature": True}` as fallback if `options` is `None` or if
`verify_signature` is not set in it.
Closes #2977
=> fix: Remove use of deprecated pyjwt parameter

allauth/templates/account/password_reset_from_key.html
The reason why this is not needed is because on successful password reset, this template is not shown, 'password_reset_from_key_done.html' is used instead
=> Remove unused condition to show success message on successful password reset

allauth/account/views.py
The issue was introduced with [that PR](https://github.com/pennersr/django-allauth/pull/2995) which is released under the version 0.48 and it does not correspond to the docs, where we mentioned about [reset_token_url](https://github.com/pennersr/django-allauth/pull/2995/files#diff-0d16353e7f1a8593229f982c23d4c0b092c7840b7a2d9bfd15c4088f70741ec1R20) and not `internal_reset_token_url`.
That was introduced by myself so we should follow the [initial issue](https://github.com/pennersr/django-allauth/issues/2892) where we should follow the [initial Django's PR](https://github.com/django/django/commit/58df8aa40fe88f753ba79e091a52f236246260b3) related to it
=> Fix naming from 'internal_reset_url_token' to 'reset_url_token' in PasswordResetFromKey view

allauth/socialaccount/providers/lemonldap/provider.py, allauth/socialaccount/providers/lemonldap/tests.py, allauth/socialaccount/providers/lemonldap/urls.py, allauth/socialaccount/providers/lemonldap/views.py, docs/installation.rst, docs/overview.rst, docs/providers.rst, test_settings.py
LemonLDAP::NG (https://lemonldap-ng.org/welcome/) is a web SSO server that supports the OpenID Connect protocol. This implementation is based on existing OAuth2 code
=> feat(providers): add LemonLDAP::NG 

allauth/socialaccount/providers/kakao/provider.py
According to Kakao official document ([Response of Retrieve user information](https://developers.kakao.com/docs/latest/en/kakaologin/rest-api#req-user-info) section), `kakao_account` is not required. If you don't set any consent items in Kakao Login settings, `kakao_account` does not exist in the response. See the [Consent Items](https://developers.kakao.com/docs/latest/en/kakaologin/prerequisite#consent-item) for more information.
Because of this, KeyError occurred in my project, and I found this bug. I also confirmed that `kakao_account` was in the response when any consent items were set.
I followed this [commit](https://github.com/pennersr/django-allauth/commit/dc66e01dacd3881a46c12241bb8f5820726e04d8).
Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar …
=> fix(kakao): Prevent 'kakao_account' KeyError

ChangeLog.rst, allauth/socialaccount/providers/facebook/provider.py, docs/providers.rst
Let's upgrade the default Facebook Graph API version to v13.0 because v7.0 will become unusable on August 4, 2022 according to https://developers.facebook.com/docs/graph-api/changelog/.
=> feat(Facebook): set the default Graph API version to v13.0

allauth/socialaccount/providers/gitea/views.py
=> Gitea provider does not work by default with gitea.com

.github/workflows/ci.yml, AUTHORS, ChangeLog.rst, allauth/account/tests.py, allauth/socialaccount/tests.py, setup.py, test_settings.py, tox.ini
=> feat: Support Django 4.1

allauth/account/forms.py, allauth/socialaccount/adapter.py, allauth/socialaccount/providers/base/provider.py, allauth/socialaccount/providers/dataporten/views.py, allauth/socialaccount/providers/trainingpeaks/views.py, docs/providers.rst
There are small typos in:
- allauth/account/forms.py
- allauth/socialaccount/adapter.py
- allauth/socialaccount/providers/base/provider.py
- allauth/socialaccount/providers/dataporten/views.py
- allauth/socialaccount/providers/trainingpeaks/views.py
- docs/providers.rst
Fixes:
- Should read `overridden` rather than `overriden`.
- Should read `validation` rather than `validaton`.
- Should read `setting` rather than `seting`.
- Should read `registered` rather than `registed`.
- Should read `authentication` rather than `athentication`.
- Should read `address` rather than `adress`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

allauth/locale/es/LC_MESSAGES/django.po
`Signup` and `Sign Up` should be translated as `Registrarse` (without tilde) instead of `Regístrarse`, as that word is stressed on the penultimate syllable, not on the third-to-last syllable.
Reference (in Spanish): [Diccionario panhispánico de dudas](https://www.rae.es/dpd/tilde)
=> fix(locale): Fixed some translations to Spanish

docs/providers.rst
Using the latest Keycloak version (19), the example `KEYCLOAK_URL` produces an invalid provider login URL - the trailing "auth" is wrong.
=> Updated keycloak config example to generate valid provider_login_url

docs/templates.rst
Since I disabled the username field for my project, I struggled to understand how to display user email in template tags.
Until I simply used {{ user }} tag, after trying to override the view and the form to custom the get_context_data to retrieve the email.
I thought it could be useful to add it clearly in your documentation.
Your lib and documentation is great by the way, thanks for your work!
=> fix(template tags): Update templates.rst

docs/configuration.rst
The old behavior is a blockquote instead of a line continuation, as seen in https://django-allauth.readthedocs.io/en/latest/configuration.html
=> docs: formatting problem

docs/signals.rst
The sentence `Sent after a user connects a social account to a their local account` should not contain the second `a` in there. Removed that.
=> fix(documentation): Fix grammar in Signals documentation

allauth/locale/nl/LC_MESSAGES/django.po
* Fixed a wrong translation of "again"
* Fixed spelling for "privé"
* Changed "wissen" to "verwijderen" to be more in line with other translations
* Made some translations more natural
=> fix(locale): Updated Dutch translations

allauth/socialaccount/providers/keycloak/views.py
Keycloak v20.0.0 does not support fetching userinfo with POST.
=> Fetch keycloak userinfo with GET

allauth/socialaccount/providers/microsoft/views.py
Extended the Microsoft Graph provider to give the companyName of the user while calling the graph API.
=> Microsoft provider: add companyName to user_properties

allauth/socialaccount/providers/facebook/provider.py, docs/providers.rst
This change makes the Facebook Graph API URL configurable via a provider setting which enables use-cases such as overriding the endpoint during integration tests to talk to a fake version of the API.
=> feat(facebook): Make Graph API URL configurable

allauth/socialaccount/providers/apple/views.py
Fixes https://github.com/pennersr/django-allauth/issues/2821. `HttpResponseNotAllowed` is not an exception, so it cannot be raised and must be returned instead.
=> fix(apple): return HttpResponseNotAllowed instead of trying to raise it

allauth/socialaccount/providers/openid_connect/provider.py
only common fields are used to populate user attributes and email was missing
Closes #3241
=> fix(openid-connect): add missing email to common fields

allauth/socialaccount/providers/oauth2/utils.py
Set the length of the generated PKCE code verifier to exactly 128 characters, as it is the maximum length allowed by RFC 7636. Using the maximum length adds entropy and, by this, security.
fixes pennersr/django-allauth#3237
=> fix(oauth2): Set PKCE Code Verifier length to 128

allauth/socialaccount/providers/openid_connect/provider.py
Keycloak provider binds to wrong base url since the slug is inherited from the hard coded `OpenIDConnectProvder` `get_slug` method. Changed the method to fallback to `super().get_slug()`.
=> fix: OpenID provider slug fallback when no server_id present (fixes #3282)

allauth/socialaccount/providers/exist/provider.py, allauth/socialaccount/providers/exist/views.py, docs/providers.rst
The v1 API has been removed completely.
- Fixed the profile url.
- Fixed the payload returned from the profile url.
- Set the default scopes when accessing attribute data.
=> fix: upgrade to Exist.io API v2

allauth/socialaccount/providers/google/views.py
This is a change similar to https://github.com/pennersr/django-allauth/pull/3187. This pull request makes the Google API URL configurable via a provider setting which enables use-cases such as overriding the endpoint during integration tests to talk to a fake version of the API.
=> feat(google): Make API URLs configurable

allauth/account/models.py, allauth/account/tests.py
There is possible to get raise conditions. I.e.
1. allauth update email field of the user in the memory
2. another process update some other user fields
3. allauth save user into DB and this will override all changes on step 2
My point that is better to specify fields to update, in order to keep changes(https://docs.djangoproject.com/en/4.0/ref/models/instances/#specifying-which-fields-to-save).
But cons of that solution that could be some fields that should be updated on the user save, ie `updated_at` and because it's not specified they wont updated during save.
=> save only updated fields

allauth/templates/account/base.html
In b82ed9efcc592eb45cc7f28a9e9f00035c55f050, `trans` tags have been introduced in the account/base.html template but the i18n module has not been loaded, resulting in errors when trying to render the default templates.
=> fix(i18n): Load i18n in account base template

allauth/account/forms.py
Currently, the password reset email template gets passed the full URL to
the password reset endpoint. However, in some scenarios, this endpoint
isn't the location where the user will actually perform the password
reset data entry, for example if Django only hosts an API backend and
the user-facing part instead is implemented via a SPA.
To make it easier to integrate such setups with allauth, this change
additionally passes the uid and key to the password reset email
template. This provides full control to the template author to generate
their own password reset links and support a split frontend/backend.
=> feat(accounts): add key to password reset template

allauth/socialaccount/adapter.py, allauth/socialaccount/helpers.py
This pull request moves all uses of `reverse("socialaccount_connections")` into the social account adapter so that they can be consistently overwritten in just one place. There was already a helper method for to format the redirect URL, but it wasn't used in all edge cases.
Besides increasing code consistency, the changes in this pull request also fix using django-allauth in combination with [dj-rest-auth](https://github.com/iMerica/dj-rest-auth/) in the scenario where we have an existing account for a new social login. Previously, we would experience a crash unless a dummy URL is configured for `socialaccount_connections`. After the fix in this PR is merged, instead of setting this dummy URL we can now override the redirect URL in the adapter which is much cleaner.
=> fix(socialaccount): Remove hard-coded redirect URL

allauth/templates/account/email/password_reset_key_message.txt
The email sent when a password reset is requested by a user states that a password was requested. Added reset to improve clarity
=> fix(accounts): Typo fix in password reset message

allauth/socialaccount/providers/google/views.py
Now the google provider will property use SOCIALACCOUNT_PROVIDERS["google"]["AUTHORIZE_URL"] as the AUTHORIZE_URL if overriden from the default.
=> fix(google): Fix google AUTHORIZE_URL settings config name

AUTHORS, allauth/socialaccount/providers/__init__.py, allauth/socialaccount/tests.py
Resolves https://github.com/pennersr/django-allauth/issues/393
This PR allows you to relabel a provider's overly generic app label (i.e., `facebook`, `google`, etc.) by defining a custom `AppConfig` subclass. This allows you to resolve conflicting app labels within your Django project. For example:
```python
class CustomFacebookAppConfig(AppConfig):
name = "allauth.socialaccount.providers.facebook"
label = "allauth_facebook" # Let's relabel allauth's Facebook provider app. 
INSTALLED_APPS = [
"example.apps.CustomFacebookAppConfig",
"facebook", # Now we can have an app called "facebook" in our Django project.
]
```
Previously, using a custom `AppConfig` resulted in the provider not being loaded at all because of how [`allauth` accesses the `INSTALLED_APPS` setting …
=> fix(providers): Load providers using their app name

allauth/socialaccount/providers/apple/views.py
##
This code handles [this problem](https://github.com/pennersr/django-allauth/pull/2424#discussion_r465940292) in issue #2424 .
In case of first sign in in app, there are no `apple_login_session["id_token"]`. Existing code is overriding `"id_token"` value with `None`. It makes `OAuth2Error("Invalid id_token")`.
However, in `access_token_data`, there is `id_token` value that almost always comes from apple api server. So this code make up `id_token` value by one valid value of two variable dict.
Base of this code is @bcarradini.
=> fix (apple): id_token missing by overriding access_token_data handling

allauth/account/adapter.py, allauth/account/tests/test_utils.py
Like those who have come before me (https://github.com/pennersr/django-allauth/pull/3264), I ran into an issue where I was unable to redirect to an absolute URL after a user successfully logs in. However, the above fix doesn't take into consideration wildcard ('*') domain matching. 
The main issue is that in `is_safe_url`, `allowed_hosts` defaults to `None` and doesn't take into account Django's standard ALLOWED_HOSTS setting.
Hopefully we can put this [issue](https://github.com/pennersr/django-allauth/issues/1766) to rest finally!
=> fix(is_safe_url): respect allowed_hosts

setup.py
[`python -m build`](https://pypi.org/project/build) still builds the same package after this change.
=> chore: Remove unnecessary `find_package_data` from setup.py

allauth/account/app_settings.py, allauth/socialaccount/app_settings.py
Module-level `__getattr__` is supported since Python 3.7.
=> Settings: Use module-level __getattr__ instead of sys.modules hack

.editorconfig, ChangeLog.rst, allauth/account/adapter.py, allauth/account/app_settings.py, allauth/account/forms.py, allauth/account/managers.py, allauth/account/models.py, allauth/account/tests/test_change_email.py, allauth/account/views.py, allauth/templates/account/email.html, allauth/templates/account/email_change.html, allauth/templates/account/snippets/warn_no_email.html, docs/configuration.rst
With these changes, when `ACCOUNT_MAX_EMAIL_ADRESSES=1`, the user can still change his email. The user is allowed to add an extra email, and when that email is confirmed, the former email is removed. So, the user is allowed to go over the maximum of 1 for the purpose of changing his email.
=> feat(account): Add `ACCOUNT_CHANGE_EMAIL` flow

allauth/templates/account/password_reset_from_key.html
This was the only form missing a css class needed to style the account's templates.
=> add css class to password_reset_from_key form

ChangeLog.rst, allauth/account/managers.py, allauth/socialaccount/app_settings.py, allauth/socialaccount/conftest.py, allauth/socialaccount/models.py, allauth/socialaccount/tests/test_login.py, docs/configuration.rst
Consider a scenario where a social login occurs, and the social account comes with a verified email address (verified by the account provider), but that email address is already taken by a local user account. Additionally, assume that the local user account does not have any social account connected. Now, if the provider can be fully trusted, you can argue that we should treat this scenario as a login to the existing local user account even if the local account does not already have the social account connected, because -- according to the provider -- the user logging in has ownership of the email address.  This is how this scenario is handled when `SOCIALACCOUNT_EMAIL_AUTHENTICATION` is set to `True`. As this implies that an untrustworthy provider can login to any local account by …
=> feat(socialaccount): Authenticate by email

AUTHORS, allauth/socialaccount/providers/telegram/provider.py, allauth/socialaccount/providers/telegram/views.py, docs/providers/telegram.rst
Added the ability to set the period for checking outdated data when authorizing via telegram.
=> Settings for checking outdated data when authorizing via telegram.

allauth/socialaccount/providers/oauth/client.py, allauth/socialaccount/providers/oauth/views.py
This PR shows helpful errors logs when the oauth error is raised
=> chore(oauth): show an informative log when OAuthError is raise

ChangeLog.rst, allauth/account/adapter.py, allauth/account/admin.py, allauth/account/forms.py, allauth/account/middleware.py, allauth/account/models.py, allauth/account/tests/test_signup.py, allauth/account/tests/test_utils.py, allauth/account/utils.py, allauth/account/views.py, allauth/conftest.py, allauth/core/context.py, allauth/mfa/adapter.py, allauth/mfa/views.py, allauth/socialaccount/adapter.py, allauth/socialaccount/forms.py, allauth/socialaccount/helpers.py, allauth/socialaccount/models.py, allauth/socialaccount/providers/base/provider.py, allauth/socialaccount/providers/draugiem/views.py, allauth/socialaccount/providers/facebook/views.py, allauth/socialaccount/providers/google/tests.py, allauth/socialaccount/providers/saml/utils.py, allauth/socialaccount/providers/steam/provider.py, allauth/socialaccount/providers/telegram/views.py, allauth/socialaccount/templatetags/socialaccount.py, allauth/socialaccount/tests/__init__.py, allauth/socialaccount/tests/test_login.py, allauth/socialaccount/tests/test_signup.py
The availability of `request` throughout the code is not consistent. Some methods get `request` passed explicitly, some don't, and some constructs have it available both as a parameter and as `self.request`. Having `request` available is essential, especially when trying to implement adapter hooks, though littering the code base with an explicit `request` is not very great.
With the changes made here, there is always a request available if you need it: `allauth.core.context.request`.
=> refactor: Provide request context

allauth/account/forms.py, allauth/socialaccount/providers/notion/provider.py, docs/account/forms.rst, docs/account/views.rst, docs/mfa/introduction.rst, docs/socialaccount/providers/miro.rst
Hi @pennersr, this is my first PR. I fix a few typos.
I guess this should read `YandexAccount` (not YandexAccout)
https://github.com/pennersr/django-allauth/blob/711395cf7ac0322beedd7b97fd900671a95bda5f/allauth/socialaccount/providers/yandex/provider.py#L7
But I was unsure, because this might break something.
=> chore: fix typos

allauth/locale/uk/LC_MESSAGES/django.po
Related to https://github.com/pennersr/django-allauth/pull/3470
=> fix(i18n): Fix i18n for Ukrainian language

docs/mfa/configuration.rst
- [] All Python code must formatted using Black, and clean from pep8 and isort issues.
- [] JavaScript code should adhere to [StandardJS](https://standardjs.com).
- [] If your changes are significant, please update `ChangeLog.rst`.
- [] If your change is substantial, feel free to add yourself to `AUTHORS`.
During development, I noticed that the MFA configuration documentation references a setting key named `MFA_TOTP_ISSUES`. However, it appears that the accurate key should be `MFA_TOTP_ISSUER`.
This pull request corrects the `MFA_TOTP_ISSUES` key to the accurate `MFA_TOTP_ISSUER` in the documentation. This minor adjustment will help to prevent potential confusion for developers who refer to the document …
=> fix(docs): fix typo in mfa configuration document

allauth/socialaccount/providers/openstreetmap/views.py
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)
=> fix(openstreetmap): Update provider url

docs/socialaccount/providers/microsoft.rst
=> Update microsoft.rst for single tenant configuration

allauth/socialaccount/migrations/0001_initial.py
=> Update 0001_initial.py for migration bug fix

.github/workflows/ci.yml, ChangeLog.rst, setup.cfg, tox.ini
Hello 👋 thank you for maintaining this package!!!
We wanted to help set up testing against Django 5.0. It's still a little early (won't be released until December) but this hopefully gives the basic structure and we can update it when wanted.
=> chore(ci): Update to add Django 5.0 (alpha) support.

allauth/templates/account/verified_email_required.html, allauth/templates/socialaccount/login_cancelled.html
Fix https://github.com/pennersr/django-allauth/issues/3503 by adding missing {% load allauth %} to define {% element %} tag.
=> Load allauth

allauth/locale/az/LC_MESSAGES/django.po
=> chore(i18n): Add Azerbaijani translation

.github/workflows/ci.yml, allauth/mfa/tests/test_views.py
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/g/gnutls28/libgnutlsxx28_3.7.3-4ubuntu1.2_amd64.deb  404  Not Found
=> fix(ci): Build broken libgnutlsxx not found

allauth/mfa/forms.py
This small change also makes it a little easier to detect the field in custom form templates (e.g. with `django-widget-tweaks`).
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#sect16
=> fix(mfa): Use "one-time-code" autocomplete hint

allauth/socialaccount/helpers.py, allauth/socialaccount/models.py
Commit https://github.com/pennersr/django-allauth/commit/be779dfee5a328a3a42edc2c95320ad00a4c7833 broke the ability to create new sociallogin accounts in Mailman3 when using django sites framwork, because the request object is not passed down the call chain.  This eventually results in the error:
> Exception Type: ImproperlyConfigured at /accounts/google/login/callback/
> Exception Value: You're using the Django "sites framework" without having set the SITE_ID setting. Create a site in your database and set the SITE_ID setting or pass a request to Site.objects.get_current() to fix this error.
This patch (optionally) passes the request object to resolve this issue.
=> fix(socialaccount): Allow new sociallogin accounts to establish SITE_ID from request

ChangeLog.rst, allauth/account/app_settings.py, allauth/account/forms.py, allauth/account/tests/test_reset_password.py, docs/account/configuration.rst
Add a setting to the accounts app which disables sending emails to addresses which do not have an account.
For many sites this behaviour will be undesirable since it sends potentially unsolicited email to someone who has not shared it with us.
=> feat(accounts): Allow disabling email sending to unknown addresses

allauth/locale/ja/LC_MESSAGES/django.po
As I rewrited only locale/ja/django.po, the list below not fits.
But all the changes (except one) I've checked by my eyes and the command `python manage.py compilemessages` worked properly.
The onlye one I've yet to check was below. checked msgid_plural but not plural one not.
```
#: templates/mfa/index.html:47 templates/mfa/recovery_codes/index.html:9
#, python-format
msgid ""
"There is %(unused_count)s out of %(total_count)s recovery codes available."
msgid_plural ""
"There are %(unused_count)s out of %(total_count)s recovery codes available."
msgstr[0] "利用可能なリカバリーコードは%(unused_count)s個中%(total_count)s個です。"
msgstr[1] "利用可能なリカバリーコードは%(unused_count)s個中%(total_count)s個です。"
```
Please feel free to provide …
=> translated texts about two factor auth related ones.

examples/regular-django/README.rst
The README's cloning instructions using the git:// URL have been updated to the SSH format. This change addresses the deprecation of unauthenticated git protocol (git://) by GitHub, which is no longer supported as of their security policy update.
See GitHub's security announcement for more details: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
=> fix(readme): Update cloning URL to use SSH format

allauth/account/forms.py
Fix typo in docstring on try_save method of BaseSignupForm
=> Fix typo in forms.py

docs/mfa/introduction.rst
Being pretty new to Django, I couldn't get mfa up and running just by looking at the docs, and I found an [SO question](https://stackoverflow.com/q/77186177/10753968) that shows other users have also had this issue.
The missing instruction was to include the `allauth.mfa` app in `settings.py` so I added that to the docs.
=> docs(mfa): Added instructions for settings.py

docs/socialaccount/providers/openid_connect.rst
Previously the use of OAUTH_PKCE_ENABLED was not documented for the generic OIDC provider even though it's supported. This adds it to the example config to guide people to add it with the correct nesting, instead of as an APP specific configuration option. The example shows `True` since it's a more secure alternative than not enabling it.
=> docs(openid_connect): Document usage of OAUTH_PKCE_ENABLED

allauth/templates/account/email_change.html, allauth/templates/allauth/elements/field.html, allauth/templates/mfa/totp/activate_form.html
I ran across a few HTML validation issues in the Django templates:
- an interleaved `slot` template tag that caused a closing `span` HTML tag to be dropped (for a field element with help text)
- some empty `for` attributes for `label`s on several pages
=> fix(templates): HTML validation issues

ChangeLog.rst, docs/installation/quickstart.rst, docs/socialaccount/introduction.rst, docs/socialaccount/providers/openid.rst, docs/socialaccount/providers/steam.rst, examples/react-spa/backend/requirements.txt, examples/regular-django/README.org, examples/regular-django/requirements.txt, setup.cfg, tox.ini
When using allauth without any of the social account functionality, do not pull in requests, JWT, ...
=> feat: Separate dependencies for socialaccount

allauth/locale/ru/LC_MESSAGES/django.po
=> fix(locale): Correct spelling mistakes and add new translation

allauth/account/utils.py
Small performance improvement by replacing prefetch_related with select_related. We can do that here because it's a ForeignKey, not a M2M relationship. This leads to performing a single database request vs 2 when using prefetch.
`(0.001) SELECT "account_emailaddress"."id", "account_emailaddress"."user_id", "account_emailaddress"."email", "account_emailaddress"."verified", "account_emailaddress"."primary", "user_user"."last_login", "user_user"."created_at", "user_user"."updated_at", "user_user"."id", "user_user"."username", "user_user"."email", "user_user"."avatar", "user_user"."password", "user_user"."score", "user_user"."is_creator", "user_user"."date_of_birth", "user_user"."is_active", "user_user"."is_superuser", "user_user"."is_staff" FROM "account_emailaddress" INNER JOIN "user_user" …
=> Feat(accounts): Use select_related instead of prefetch_related

ChangeLog.rst, allauth/account/mixins.py, allauth/account/tests/test_change_password.py, allauth/account/tests/test_confirm_email.py, allauth/account/tests/test_reset_password.py, allauth/account/utils.py, allauth/account/views.py, allauth/socialaccount/providers/facebook/provider.py, allauth/socialaccount/providers/openid/views.py, allauth/socialaccount/templatetags/socialaccount.py, allauth/templates/account/email_confirm.html, allauth/templates/account/login.html, allauth/templates/account/logout.html, allauth/templates/account/password_change.html, allauth/templates/account/password_reset_from_key.html, allauth/templates/account/password_set.html, allauth/templates/account/reauthenticate.html, allauth/templates/account/signup.html, allauth/templates/mfa/reauthenticate.html, allauth/templates/socialaccount/signup.html
=> refactor: Proper ?next= redirect handling throughout

allauth/socialaccount/providers/slack/provider.py, allauth/socialaccount/providers/slack/views.py
The problem I am having is when oauth from Slack I always get a login failure error. After comparing with Slack document I think the issue is due to Slack new endpoint and oauth response change. I have tested this patch in my app and can sign in Slack.
From Slack [document](https://api.slack.com/authentication/sign-in-with-slack#discover)
The new endpoints are:
```
"authorization_endpoint": "https://slack.com/openid/connect/authorize",
"token_endpoint": "https://slack.com/api/openid.connect.token",
"userinfo_endpoint": "https://slack.com/api/openid.connect.userInfo",
``` 
And team_id along with user_id are changed too from [here](https://api.slack.com/authentication/sign-in-with-slack#response)
```
"https://slack.com/team_id": "T0123ABC456",
"https://slack.com/user_id": "U123ABC456",
``` …
=> fix(slack): Handle new slack openid endpoint and token response

allauth/locale/et/LC_MESSAGES/django.po
Provides Estonian translations.
Some formatting and metadata in the header might be off since I was getting the following error when running `makemessages`:
```
CommandError: Unable to find a locale path to store translations for file examples/react-spa/backend/backend/__init__.py. Make sure the 'locale' directory exists in an app or LOCALE_PATHS setting is set.
```
Please let me know if there is anything else that needs to be done before the changes can be accepted.
Thanks!
=> feat(i18n): add Estonian (`et`) translations

README.rst
_Hello @pennersr,_
I noticed that you recently dropped some `SVG` badges in b24e4310552a03839ad352e3316a06afd66489d8 and f4e4276ced68318fe1d6327978b25515a3857d66, but I believe this change might be reconsidered taking into account how poorly scaled `PNG`s might look.
Raster badges look blurry at scales different from 100%, so it's worth switching to vector badges which look fine at any scale.
_Raster badges at 170% scale on my machine:_
_Vector badges at 170% scale on my machine:_
_Best regards!_
=> 🖌️ Use vector badges

allauth/locale/ja/LC_MESSAGES/django.po
The original translation mistakenly swapped the placeholders for `unused_count` and `total_count`. This error could lead to confusion regarding the number of available recovery codes. The correction ensures that the message accurately reflects the number of unused recovery codes out of the total available.
- Incorrect: "利用可能なリカバリーコードは %(unused_count)s 個中 %(total_count)s 個です。"
- Corrected: "利用可能なリカバリーコードは %(total_count)s 個中 %(unused_count)s 個です。"
This change rectifies the order of the placeholders to properly convey the intended message to the users.
Additionally, I have translated all remaining untranslated sections while making this correction.
=> chore(i18n): Add japanese translation and fix mistranslation

allauth/account/adapter.py
Currently, the characters that are forbidden are just the ones that resemble other characters ([source](https://github.com/pennersr/django-allauth/blob/0.62.1/allauth/account/adapter.py#L749)):
1. `0` and `O`
1. `I` and `1`
1. `8` and `B`
1. `2` and `Z`
I think it would be good to also forbid A, E, and U. As it is now, it is possible for the code to spell something potentially offensive or off-putting such as "URLAME" or "CANCER".
=> fix(accounts): Login by code: also forbid A, E, and U

ChangeLog.rst, allauth/account/managers.py, allauth/account/migrations/0006_emailaddress_lower.py, allauth/account/migrations/0007_emailaddress_idx_email.py, allauth/account/models.py, allauth/account/utils.py
Formally, email addresses are case sensitive because the local part (the part before the "@") can be a case sensitive user name.  To deal with this, workarounds have been in place for a long time that store email addresses in their original case, while performing lookups in a case insensitive style. This approach led to subtle bugs in upstream code, and also comes at a performance cost (``__iexact`` lookups). The latter requires case insensitive index support, which not all databases support. Re-evaluating the approach in current times has led to the conclusion that the benefits do not outweigh the costs.  Therefore, email addresses are now always stored as lower case, and migrations are in place to address existing records.
=> feat(account): Store emails lower case, treat case insensitive

allauth/utils.py
When serializing BinaryField(blank=True, null=True) containing None value an exception is thrown:
```
TypeError at /accounts/google/login/callback/ a bytes-like object is required, not 'None Type'
```
This patch kinda fixes the problem.
=> fix: Cannot serialize BinaryField wihout a value

allauth/account/checks.py
This setting name appears to be incorrect (unless a change is pending that `main` does not yet reflect; sorry to waste your time in that case). Perhaps this will save someone a few minutes of confusion.
=> Fix ACCOUNT_EMAIL_VERIFICATION setting name in checks.py message

allauth/account/tests/test_login.py, allauth/usersessions/tests/test_views.py, tox.ini
- Fixed a small typo in `account/test_login.py`.
- Added a new test which tests 'login while authenticated.' This fails in 0.62.1 and was problematic in case one wants to mimic the behavior of Django admin login view, where it allows to authenticate with new credentials if the current user is not permitted to access the admin pages. Fortunately, this got fixed in the current main branch ([code](https://github.com/pennersr/django-allauth/blame/55297fabe73328a711477d82a781e140ec178921/allauth/usersessions/models.py#L34)) but I thought it deserves a new test to prevent from breaking again in future developments (and perhaps a new entry in change log too?).
- Changed `tox` …
=> chore(tests): Fix and add tests

allauth/headless/internal/authkit.py
This commit complements #3785 . Even though the headless API won't attach a session token when user logs out, the empty session is still created in the database upon exiting the context manager `authentication_context()`. This patch fixes this by also checking if the session is empty within the context manager.
Note: this behavior is quite tricky to test, because normally there is no way to access the 'ghost' session. If the session backend is guaranteed to be database-backed, then one way is to check the number of sessions before and after logout. The test code may be slightly messy though - I'll add a test if requested.
=> fix(headless): Do not create an empty session in app context on logout

docs/common/templates.rst
This is a quick fix to documentation. entrance.html refers to the entrance template, and manage.html refers to the management template, not the other way around.
=> docs: fix table in templates.rst

docs/socialaccount/providers/google.rst
This updates the document for the Google provider. It updates the instructions on how to create a new OAuth Client ID, matching Google's new interface. It mentions that `pyjwt[crypto]` should be installed (installing `pyjwt` by itself is not enough). It also mentions adding the correct provider to `INSTALLED_APPS`.
=> docs: Update google.rst

allauth/mfa/adapter.py, allauth/mfa/internal/flows/authentication.py, allauth/mfa/internal/flows/recovery_codes.py, allauth/mfa/internal/flows/totp.py, allauth/mfa/models.py, allauth/mfa/recovery_codes.py, allauth/mfa/totp.py
This PR adds a bunch of types to `allauth.mfa`'s internals.
Our app needs to set up MFA with a slightly custom flow, so we can't use the forms or headless features, so I needed to delve a bit into how things work under the hood, and figured it'd be useful if types were documented technically too, for IDEs etc.
Feels like `TOTP` and `RecoveryCodes` should have a superclass, but that's beyond the scope of this PR...
=> fix(mfa): Add types to `allauth.mfa` flows

allauth/templates/allauth/elements/field.html
The `<label>` element should be placed before its corresponding <input> in most cases. However, in the case of a checkbox input or a radio input, the <label> element should be placed after it.
To illustrate:
Bad:
I agree to terms and conditions ☑
Good:
☑ I agree to terms and conditions
django-allauth ships with the two templates that will be affected positively by this change:
allauth/templates/account/email.html
allauth/templates/socialaccount/connections.html
=> Render checkboxes and radio buttons before label

allauth/account/middleware.py
Although staticfiles is typically enabled by most projects, it is not strictly required by Allauth.
=> fix(account): Fix an error when staticfiles is not enabled

allauth/templates/allauth/elements/button_group.html, allauth/templates/allauth/elements/h1.html, allauth/templates/allauth/elements/h2.html, allauth/templates/allauth/elements/p.html, allauth/templates/allauth/elements/provider_list.html, docs/common/templates.rst, examples/regular-django/example/templates/allauth/elements/button_group.html, examples/regular-django/example/templates/allauth/elements/h1.html, examples/regular-django/example/templates/allauth/elements/h1__entrance.html, examples/regular-django/example/templates/allauth/elements/h2__entrance.html, examples/regular-django/example/templates/allauth/elements/provider_list.html
This better matches the way they're invoked (with no explicit name), making them simpler to understand.
This also adds documentation about both default and named slots.
=> refactor(templates): Inject "default" slots with their implicit syntax

allauth/socialaccount/providers/bitbucket_oauth2/views.py, allauth/socialaccount/providers/github/views.py
I encountered this situation by having the following context.
First, I have this social account configuration:
```python
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
"google": {
"APP": {
"client_id": getenv("GOOGLE_OAUTH_CLIENT_ID"),
"secret": getenv("GOOGLE_OAUTH_CLIENT_SECRET"),
}
},
"github": {
"APP": {
"client_id": getenv("GITHUB_OAUTH_CLIENT_ID"),
"secret": getenv("GITHUB_OAUTH_CLIENT_SECRET"),
}
},
}
```
Next, I took these steps:
1. Register a new user w/ email and password, `foo@bar.com`.
2. I configured a GH OAuth application and provider.
3. I hit the `github_login` view to initiate the process of linking my GitHub user w/ email address `foo@bar.com` to my local user …
=> fix: Always fetch emails when QUERY_EMAILS is set

docs/headless/openapi-specification/openapi.yaml
The endpoint isn't correct. Django returns a 404 for /account/webauthn, but /account/authenticators/webauthn seems to work.
=> fix(docs): Fixed WebAuth api endpoint URI in OpenAPI spec

tox.ini
Fixes these warnings seen during tests on Python 3.12:
```
/.../coverage/pytracer.py:223: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
self.thread = self.threading.currentThread()
...
/.../coverage/parser.py:382: DeprecationWarning: co_lnotab is deprecated, use co_lines instead.
if not hasattr(self.code, attr):
```
The last one is repeated many times.
Coverage 7.6.1 is compatible with Python 3.8-3.12, so perfect for the range tested here.
=> tests: Upgrade coverage to 7.6.1

allauth/locale/uz/LC_MESSAGES/django.po
I am a native Uzbek speaker. I am using this package in my projects, so I thought it would be a good idea to translate it for myself & other potential users.
=> feat(i18n): Added Uzbek translations

allauth/account/adapter.py, allauth/account/forms.py
Related to https://github.com/pennersr/django-allauth/issues/4024.
=> feat(account): Move RequestPasswordReset.save impl into account adapter

allauth/templates/mfa/index.html, allauth/templates/mfa/webauthn/authenticator_confirm_delete.html, allauth/templates/mfa/webauthn/authenticator_list.html
!close #4062 Use the p element in passkey-related templates, instead of <p> HTML tags
=> fix: use {% element p %} instead of raw <p> HTML tags.

allauth/socialaccount/providers/facebook/templates/facebook/fbconnect.html, allauth/socialaccount/providers/telegram/templates/telegram/callback.html, allauth/templates/account/email.html, allauth/templates/mfa/authenticate.html, allauth/templates/mfa/webauthn/reauthenticate.html, allauth/templates/mfa/webauthn/snippets/login_script.html, allauth/templates/mfa/webauthn/snippets/scripts.html
The “type” attribute is unnecessary for JavaScript resources. The default type for <script> tags is JavaScript, so you don’t need to include the type for JS resources.
=> fix: remove the type attribute from <script> tags

docs/socialaccount/providers/cern.rst
Update CERN provider links, add clarifications to the description
=> docs: update CERN provider
